; Generated by cc64 from tests/graphics.c
; Assemble with: c64asm tests/graphics.asm -o program.prg
 
; ---- zero page pseudo-registers ---------------------------------
; Only $02/$03 and $FB-$FE are used here. Per the KERNAL's own
; memory map, those are the ONLY zero-page bytes confirmed genuinely
; free: $F3/$F4 is the current-line-in-color-RAM pointer (touched by
; CHROUT itself when it colors a printed character) and $F5/$F6 is the
; keyboard-matrix-to-PETSCII conversion table pointer (touched by the
; keyboard scan on every background IRQ, ~60x/sec) - both looked like
; safe 'adjacent' bytes but are not; this bit us for real once already.
__zpAP = $02      ; effective-address pointer (2 bytes) - needs zero
                  ; page because it's used with (zp),Y indirection
__zpR  = $FB      ; primary register / return value (2 bytes)
__zpR2 = $FD      ; secondary operand register (2 bytes)
__CHROUT = $FFD2
 
.basic
    LDA #14           ; switch to the lower/upper character set - required
    JSR __CHROUT      ; for the PETSCII case mapping below to render as letters
                      ; (the default charset only has graphics past $C0)
    LDA #0
    STA __rt_spidx
    LDA #<__rt_cstack ; call-stack pointer starts at the base of its buffer -
    STA __rt_csp      ; see codegen_stmt.c's emit_function() for how each
    LDA #>__rt_cstack ; function's push/popframe routines use it to support
    STA __rt_csp+1    ; recursion despite locals/params living at fixed addresses
    JSR __fn_main
    RTS
 
; ---- runtime scratch storage (plain RAM, NOT zero page - only __zpAP
; needs (zp),Y indirection; these are always accessed directly) -------
__rt_spidx:
    .byte 0
__rt_csp:
    .fill 2, 0
__zpT1:
    .fill 2, 0
__zpT0:
    .fill 2, 0
__rt_pi_neg:
    .byte 0
__rt_pi_ndig:
    .byte 0
__rt_pbuf:
    .fill 5, 0
__rt_ph_lo:
    .byte 0
__rt_ph_byte_sv:
    .byte 0
 
; ---- runtime library -------------------------------------------
__rt_push:
    LDX __rt_spidx
    LDA __zpR
    STA __rt_stack,X
    LDA __zpR+1
    STA __rt_stack+1,X
    INX
    INX
    STX __rt_spidx
    BNE __rt_push_ok
    LDA #<__str_1
    STA __zpR
    LDA #>__str_1
    STA __zpR+1
    JSR __rt_puts
__rt_push_halt:
    JMP __rt_push_halt
__rt_push_ok:
    RTS
 
__rt_pop2:
    LDX __rt_spidx
    DEX
    DEX
    LDA __rt_stack,X
    STA __zpR2
    LDA __rt_stack+1,X
    STA __zpR2+1
    STX __rt_spidx
    RTS
 
__rt_cstack_check:
    TSX
    CPX #$20
    BCC __rt_csc_overflow
    LDA __rt_csp+1
    CMP #>(__rt_cstack+4096)
    BCC __rt_csc_ok
    BNE __rt_csc_overflow
    LDA __rt_csp
    CMP #<(__rt_cstack+4096)
    BCC __rt_csc_ok
    BEQ __rt_csc_ok
__rt_csc_overflow:
    LDA #<__str_0
    STA __zpR
    LDA #>__str_0
    STA __zpR+1
    JSR __rt_puts
__rt_csc_halt:
    JMP __rt_csc_halt
__rt_csc_ok:
    RTS
 
__rt_mul16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_mul16_loop:
    LSR __zpR+1
    ROR __zpR
    BCC __rt_mul16_noadd
    CLC
    LDA __zpT0
    ADC __zpR2
    STA __zpT0
    LDA __zpT0+1
    ADC __zpR2+1
    STA __zpT0+1
__rt_mul16_noadd:
    ASL __zpR2
    ROL __zpR2+1
    DEX
    BNE __rt_mul16_loop
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    RTS
 
__rt_udiv16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_udiv16_loop:
    ASL __zpR2
    ROL __zpR2+1
    ROL __zpT0
    ROL __zpT0+1
    LDA __zpT0
    SEC
    SBC __zpR
    TAY
    LDA __zpT0+1
    SBC __zpR+1
    BCC __rt_udiv16_skip
    STA __zpT0+1
    STY __zpT0
    INC __zpR2
__rt_udiv16_skip:
    DEX
    BNE __rt_udiv16_loop
    RTS
 
__rt_neg_r2:
    SEC
    LDA #0
    SBC __zpR2
    TAX
    LDA #0
    SBC __zpR2+1
    STA __zpR2+1
    STX __zpR2
    RTS
 
__rt_neg_r:
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    RTS
 
__rt_neg_t0:
    SEC
    LDA #0
    SBC __zpT0
    TAX
    LDA #0
    SBC __zpT0+1
    STA __zpT0+1
    STX __zpT0
    RTS
 
__rt_sdivmod16:
    LDA #0
    STA __zpT1
    STA __zpT1+1
    LDA __zpR2+1
    BPL __rt_sdm_d1
    JSR __rt_neg_r2
    INC __zpT1
__rt_sdm_d1:
    LDA __zpR+1
    BPL __rt_sdm_d2
    JSR __rt_neg_r
    INC __zpT1+1
__rt_sdm_d2:
    JSR __rt_udiv16
    LDA __zpT1
    EOR __zpT1+1
    AND #1
    BEQ __rt_sdm_qdone
    JSR __rt_neg_r2
__rt_sdm_qdone:
    LDA __zpT1
    BEQ __rt_sdm_rdone
    JSR __rt_neg_t0
__rt_sdm_rdone:
    RTS
 
__rt_eq16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_eq16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_eq16_ne
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_eq16_ne:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_ne16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_ne16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_ne16_ne
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ne16_ne:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_sub_r2r:
    SEC
    LDA __zpR2
    SBC __zpR
    LDA __zpR2+1
    SBC __zpR+1
    BVC __rt_sub_r2r_ok
    EOR #$80
__rt_sub_r2r_ok:
    RTS
 
__rt_sub_rr2:
    SEC
    LDA __zpR
    SBC __zpR2
    LDA __zpR+1
    SBC __zpR2+1
    BVC __rt_sub_rr2_ok
    EOR #$80
__rt_sub_rr2_ok:
    RTS
 
__rt_lt16:
    JSR __rt_sub_r2r
    BMI __rt_lt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_lt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ge16:
    JSR __rt_sub_r2r
    BPL __rt_ge16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_gt16:
    JSR __rt_sub_rr2
    BMI __rt_gt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_gt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_le16:
    JSR __rt_sub_rr2
    BPL __rt_le16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_le16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_shl16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shl16_loop:
    CPX #0
    BEQ __rt_shl16_done
    ASL __zpR
    ROL __zpR+1
    DEX
    JMP __rt_shl16_loop
__rt_shl16_done:
    RTS
 
__rt_shr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shr16_loop:
    CPX #0
    BEQ __rt_shr16_done
    LDA __zpR+1
    CMP #$80
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_shr16_loop
__rt_shr16_done:
    RTS
 
__rt_ushr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_ushr16_loop:
    CPX #0
    BEQ __rt_ushr16_done
    CLC
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_ushr16_loop
__rt_ushr16_done:
    RTS
 
__rt_topetscii:
    LDA __zpR
    CMP #$61
    BCC __rt_tp_notlower
    CMP #$7B
    BCS __rt_tp_notlower
    SEC
    SBC #$20
    STA __zpR
    JMP __rt_tp_done
__rt_tp_notlower:
    CMP #$41
    BCC __rt_tp_done
    CMP #$5B
    BCS __rt_tp_done
    CLC
    ADC #$80
    STA __zpR
__rt_tp_done:
    RTS
 
__rt_ult16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_ult16_t
    BNE __rt_ult16_f
    LDA __zpR2
    CMP __zpR
    BCC __rt_ult16_t
__rt_ult16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ult16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ugt16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ugt16_t
    BNE __rt_ugt16_f
    LDA __zpR
    CMP __zpR2
    BCC __rt_ugt16_t
__rt_ugt16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ugt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ule16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ule16_f
    BNE __rt_ule16_t
    LDA __zpR
    CMP __zpR2
    BCC __rt_ule16_f
__rt_ule16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_ule16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_uge16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_uge16_f
    BNE __rt_uge16_t
    LDA __zpR2
    CMP __zpR
    BCC __rt_uge16_f
__rt_uge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_uge16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_puts:
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
__rt_puts_loop:
    LDY #0
    LDA (__zpAP),Y
    BEQ __rt_puts_done
    STA __zpR
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    CLC
    LDA __zpAP
    ADC #1
    STA __zpAP
    LDA __zpAP+1
    ADC #0
    STA __zpAP+1
    JMP __rt_puts_loop
__rt_puts_done:
    RTS
 
__rt_putc:
    STA __zpR
    JSR __rt_topetscii
    LDA __zpR
    JMP __CHROUT
 
__rt_print_hex16:
    LDA __zpR
    STA __rt_ph_lo
    LDA __zpR+1
    JSR __rt_ph_byte
    LDA __rt_ph_lo
    JSR __rt_ph_byte
    RTS
__rt_ph_byte:
    STA __rt_ph_byte_sv
    LSR A
    LSR A
    LSR A
    LSR A
    JSR __rt_ph_nibble
    LDA __rt_ph_byte_sv
    AND #$0F
    JMP __rt_ph_nibble
__rt_ph_nibble:
    CMP #10
    BCC __rt_ph_digit
    CLC
    ADC #55
    JMP __rt_putc
__rt_ph_digit:
    CLC
    ADC #48
    JMP __rt_putc
 
__rt_print_int16:
    LDA #0
    STA __rt_pi_neg
    STA __rt_pi_ndig
    LDA __zpR+1
    BPL __rt_pi_notneg
    INC __rt_pi_neg
    SEC
    LDA #0
    SBC __zpR
    STA __zpR
    LDA #0
    SBC __zpR+1
    STA __zpR+1
__rt_pi_notneg:
    LDA __zpR
    ORA __zpR+1
    BNE __rt_pi_digloop_init
    LDA __rt_pi_neg
    BEQ __rt_pi_zero
    LDA #45
    JSR __rt_putc
__rt_pi_zero:
    LDA #48
    JMP __rt_putc
__rt_pi_digloop_init:
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    LDA #10
    STA __zpR
    LDA #0
    STA __zpR+1
__rt_pi_digloop:
    JSR __rt_sdivmod16
    LDX __rt_pi_ndig
    LDA __zpT0
    STA __rt_pbuf,X
    INC __rt_pi_ndig
    LDA __zpR2
    ORA __zpR2+1
    BNE __rt_pi_digloop
    LDA __rt_pi_neg
    BEQ __rt_pi_printloop
    LDA #45
    JSR __rt_putc
__rt_pi_printloop:
    DEC __rt_pi_ndig
    LDX __rt_pi_ndig
    LDA __rt_pbuf,X
    CLC
    ADC #48
    JSR __rt_putc
    LDA __rt_pi_ndig
    BNE __rt_pi_printloop
    RTS
 
__rt_print_uint16:
    LDA #0
    STA __rt_pi_ndig
    LDA __zpR
    ORA __zpR+1
    BNE __rt_pu_digloop_init
    LDA #48
    JMP __rt_putc
__rt_pu_digloop_init:
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    LDA #10
    STA __zpR
    LDA #0
    STA __zpR+1
__rt_pu_digloop:
    JSR __rt_udiv16
    LDX __rt_pi_ndig
    LDA __zpT0
    STA __rt_pbuf,X
    INC __rt_pi_ndig
    LDA __zpR2
    ORA __zpR2+1
    BNE __rt_pu_digloop
__rt_pu_printloop:
    DEC __rt_pi_ndig
    LDX __rt_pi_ndig
    LDA __rt_pbuf,X
    CLC
    ADC #48
    JSR __rt_putc
    LDA __rt_pi_ndig
    BNE __rt_pu_printloop
    RTS
 
; ---- global variables --------------------------------------------
 
; ---- function border_color ---------------------------------------------
__fn_border_color_frame:
__fn_border_color_v_c:
    .fill 2, 0
__fn_border_color_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_border_color_pushfr_loop:
    LDA __fn_border_color_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_border_color_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_border_color_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_border_color_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_border_color_frame,Y
    INY
    CPY #2
    BNE __fn_border_color_popfr_loop
    RTS
 
__fn_border_color:
    LDA #<53280
    STA __zpR
    LDA #>53280
    STA __zpR+1
    JSR __rt_push
    LDA __fn_border_color_v_c
    STA __zpR
    LDA __fn_border_color_v_c+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function background_color ---------------------------------------------
__fn_background_color_frame:
__fn_background_color_v_c:
    .fill 2, 0
__fn_background_color_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_background_color_pushfr_loop:
    LDA __fn_background_color_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_background_color_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_background_color_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_background_color_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_background_color_frame,Y
    INY
    CPY #2
    BNE __fn_background_color_popfr_loop
    RTS
 
__fn_background_color:
    LDA #<53281
    STA __zpR
    LDA #>53281
    STA __zpR+1
    JSR __rt_push
    LDA __fn_background_color_v_c
    STA __zpR
    LDA __fn_background_color_v_c+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function plot_char ---------------------------------------------
__fn_plot_char_frame:
__fn_plot_char_v_x:
    .fill 2, 0
__fn_plot_char_v_y:
    .fill 2, 0
__fn_plot_char_v_screen_code:
    .fill 2, 0
__fn_plot_char_v_color:
    .fill 2, 0
__fn_plot_char_v_offset:
    .fill 2, 0
__fn_plot_char_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_plot_char_pushfr_loop:
    LDA __fn_plot_char_frame,Y
    STA (__zpAP),Y
    INY
    CPY #10
    BNE __fn_plot_char_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #10
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_plot_char_popframe:
    SEC
    LDA __rt_csp
    SBC #10
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_plot_char_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_plot_char_frame,Y
    INY
    CPY #10
    BNE __fn_plot_char_popfr_loop
    RTS
 
__fn_plot_char:
    LDA __fn_plot_char_v_y
    STA __zpR
    LDA __fn_plot_char_v_y+1
    STA __zpR+1
    JSR __rt_push
    LDA #<40
    STA __zpR
    LDA #>40
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_push
    LDA __fn_plot_char_v_x
    STA __zpR
    LDA __fn_plot_char_v_x+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_offset
    LDA __zpR+1
    STA __fn_plot_char_v_offset+1
    LDA #<1024
    STA __zpR
    LDA #>1024
    STA __zpR+1
    JSR __rt_push
    LDA __fn_plot_char_v_offset
    STA __zpR
    LDA __fn_plot_char_v_offset+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_plot_char_v_screen_code
    STA __zpR
    LDA __fn_plot_char_v_screen_code+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<55296
    STA __zpR
    LDA #>55296
    STA __zpR+1
    JSR __rt_push
    LDA __fn_plot_char_v_offset
    STA __zpR
    LDA __fn_plot_char_v_offset+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_plot_char_v_color
    STA __zpR
    LDA __fn_plot_char_v_color+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function clear_screen ---------------------------------------------
__fn_clear_screen_frame:
__fn_clear_screen_v_color:
    .fill 2, 0
__fn_clear_screen_v_i:
    .fill 2, 0
__fn_clear_screen_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_clear_screen_pushfr_loop:
    LDA __fn_clear_screen_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_clear_screen_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_clear_screen_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_clear_screen_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_clear_screen_frame,Y
    INY
    CPY #4
    BNE __fn_clear_screen_popfr_loop
    RTS
 
__fn_clear_screen:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_clear_screen_v_i
    LDA __zpR+1
    STA __fn_clear_screen_v_i+1
__L0:
    LDA __fn_clear_screen_v_i
    STA __zpR
    LDA __fn_clear_screen_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1000
    STA __zpR
    LDA #>1000
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L3
    JMP __L1
__L3:
    LDA #<1024
    STA __zpR
    LDA #>1024
    STA __zpR+1
    JSR __rt_push
    LDA __fn_clear_screen_v_i
    STA __zpR
    LDA __fn_clear_screen_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<32
    STA __zpR
    LDA #>32
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<55296
    STA __zpR
    LDA #>55296
    STA __zpR+1
    JSR __rt_push
    LDA __fn_clear_screen_v_i
    STA __zpR
    LDA __fn_clear_screen_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_clear_screen_v_color
    STA __zpR
    LDA __fn_clear_screen_v_color+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
__L2:
    LDA __fn_clear_screen_v_i
    STA __zpR
    LDA __fn_clear_screen_v_i+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #1
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_clear_screen_v_i
    LDA __zpR+1
    STA __fn_clear_screen_v_i+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    JMP __L0
__L1:
    RTS
 
; ---- function sprite_enable ---------------------------------------------
__fn_sprite_enable_frame:
__fn_sprite_enable_v_n:
    .fill 2, 0
__fn_sprite_enable_v_on:
    .fill 2, 0
__fn_sprite_enable_v_mask:
    .fill 2, 0
__fn_sprite_enable_v_v:
    .fill 2, 0
__fn_sprite_enable_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_enable_pushfr_loop:
    LDA __fn_sprite_enable_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sprite_enable_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_enable_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_enable_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_enable_frame,Y
    INY
    CPY #8
    BNE __fn_sprite_enable_popfr_loop
    RTS
 
__fn_sprite_enable:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_enable_v_n
    STA __zpR
    LDA __fn_sprite_enable_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    STA __fn_sprite_enable_v_mask
    LDA __zpR+1
    STA __fn_sprite_enable_v_mask+1
    LDA #<53269
    STA __zpR
    LDA #>53269
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_v
    LDA __zpR+1
    STA __fn_sprite_enable_v_v+1
    LDA __fn_sprite_enable_v_on
    STA __zpR
    LDA __fn_sprite_enable_v_on+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L6
    JMP __L4
__L6:
    LDA __fn_sprite_enable_v_v
    STA __zpR
    LDA __fn_sprite_enable_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_enable_v_mask
    STA __zpR
    LDA __fn_sprite_enable_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_v
    LDA __zpR+1
    STA __fn_sprite_enable_v_v+1
    JMP __L5
__L4:
    LDA __fn_sprite_enable_v_v
    STA __zpR
    LDA __fn_sprite_enable_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_enable_v_mask
    STA __zpR
    LDA __fn_sprite_enable_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_v
    LDA __zpR+1
    STA __fn_sprite_enable_v_v+1
__L5:
    LDA #<53269
    STA __zpR
    LDA #>53269
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_enable_v_v
    STA __zpR
    LDA __fn_sprite_enable_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_pos ---------------------------------------------
__fn_sprite_pos_frame:
__fn_sprite_pos_v_n:
    .fill 2, 0
__fn_sprite_pos_v_x:
    .fill 2, 0
__fn_sprite_pos_v_y:
    .fill 2, 0
__fn_sprite_pos_v_msb:
    .fill 2, 0
__fn_sprite_pos_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_pos_pushfr_loop:
    LDA __fn_sprite_pos_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sprite_pos_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_pos_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_pos_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_pos_frame,Y
    INY
    CPY #8
    BNE __fn_sprite_pos_popfr_loop
    RTS
 
__fn_sprite_pos:
    LDA #<53248
    STA __zpR
    LDA #>53248
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_n
    STA __zpR
    LDA __fn_sprite_pos_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_x
    STA __zpR
    LDA __fn_sprite_pos_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<53249
    STA __zpR
    LDA #>53249
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_n
    STA __zpR
    LDA __fn_sprite_pos_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_y
    STA __zpR
    LDA __fn_sprite_pos_v_y+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<53264
    STA __zpR
    LDA #>53264
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_msb
    LDA __zpR+1
    STA __fn_sprite_pos_v_msb+1
    LDA __fn_sprite_pos_v_x
    STA __zpR
    LDA __fn_sprite_pos_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L9
    JMP __L7
__L9:
    LDA __fn_sprite_pos_v_msb
    STA __zpR
    LDA __fn_sprite_pos_v_msb+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_n
    STA __zpR
    LDA __fn_sprite_pos_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_msb
    LDA __zpR+1
    STA __fn_sprite_pos_v_msb+1
    JMP __L8
__L7:
    LDA __fn_sprite_pos_v_msb
    STA __zpR
    LDA __fn_sprite_pos_v_msb+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_n
    STA __zpR
    LDA __fn_sprite_pos_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_msb
    LDA __zpR+1
    STA __fn_sprite_pos_v_msb+1
__L8:
    LDA #<53264
    STA __zpR
    LDA #>53264
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_msb
    STA __zpR
    LDA __fn_sprite_pos_v_msb+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_color ---------------------------------------------
__fn_sprite_color_frame:
__fn_sprite_color_v_n:
    .fill 2, 0
__fn_sprite_color_v_c:
    .fill 2, 0
__fn_sprite_color_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_color_pushfr_loop:
    LDA __fn_sprite_color_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_sprite_color_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_color_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_color_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_color_frame,Y
    INY
    CPY #4
    BNE __fn_sprite_color_popfr_loop
    RTS
 
__fn_sprite_color:
    LDA #<53287
    STA __zpR
    LDA #>53287
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_color_v_n
    STA __zpR
    LDA __fn_sprite_color_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_color_v_c
    STA __zpR
    LDA __fn_sprite_color_v_c+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_pointer ---------------------------------------------
__fn_sprite_pointer_frame:
__fn_sprite_pointer_v_n:
    .fill 2, 0
__fn_sprite_pointer_v_block:
    .fill 2, 0
__fn_sprite_pointer_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_pointer_pushfr_loop:
    LDA __fn_sprite_pointer_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_sprite_pointer_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_pointer_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_pointer_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_pointer_frame,Y
    INY
    CPY #4
    BNE __fn_sprite_pointer_popfr_loop
    RTS
 
__fn_sprite_pointer:
    LDA #<2040
    STA __zpR
    LDA #>2040
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pointer_v_n
    STA __zpR
    LDA __fn_sprite_pointer_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pointer_v_block
    STA __zpR
    LDA __fn_sprite_pointer_v_block+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_multicolor ---------------------------------------------
__fn_sprite_multicolor_frame:
__fn_sprite_multicolor_v_n:
    .fill 2, 0
__fn_sprite_multicolor_v_on:
    .fill 2, 0
__fn_sprite_multicolor_v_mask:
    .fill 2, 0
__fn_sprite_multicolor_v_v:
    .fill 2, 0
__fn_sprite_multicolor_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_multicolor_pushfr_loop:
    LDA __fn_sprite_multicolor_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sprite_multicolor_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_multicolor_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_multicolor_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_multicolor_frame,Y
    INY
    CPY #8
    BNE __fn_sprite_multicolor_popfr_loop
    RTS
 
__fn_sprite_multicolor:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_multicolor_v_n
    STA __zpR
    LDA __fn_sprite_multicolor_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    STA __fn_sprite_multicolor_v_mask
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_mask+1
    LDA #<53276
    STA __zpR
    LDA #>53276
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_multicolor_v_v
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_v+1
    LDA __fn_sprite_multicolor_v_on
    STA __zpR
    LDA __fn_sprite_multicolor_v_on+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L12
    JMP __L10
__L12:
    LDA __fn_sprite_multicolor_v_v
    STA __zpR
    LDA __fn_sprite_multicolor_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_multicolor_v_mask
    STA __zpR
    LDA __fn_sprite_multicolor_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_multicolor_v_v
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_v+1
    JMP __L11
__L10:
    LDA __fn_sprite_multicolor_v_v
    STA __zpR
    LDA __fn_sprite_multicolor_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_multicolor_v_mask
    STA __zpR
    LDA __fn_sprite_multicolor_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_multicolor_v_v
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_v+1
__L11:
    LDA #<53276
    STA __zpR
    LDA #>53276
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_multicolor_v_v
    STA __zpR
    LDA __fn_sprite_multicolor_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_shared_colors ---------------------------------------------
__fn_sprite_shared_colors_frame:
__fn_sprite_shared_colors_v_c1:
    .fill 2, 0
__fn_sprite_shared_colors_v_c3:
    .fill 2, 0
__fn_sprite_shared_colors_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_shared_colors_pushfr_loop:
    LDA __fn_sprite_shared_colors_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_sprite_shared_colors_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_shared_colors_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_shared_colors_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_shared_colors_frame,Y
    INY
    CPY #4
    BNE __fn_sprite_shared_colors_popfr_loop
    RTS
 
__fn_sprite_shared_colors:
    LDA #<53285
    STA __zpR
    LDA #>53285
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_shared_colors_v_c1
    STA __zpR
    LDA __fn_sprite_shared_colors_v_c1+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<53286
    STA __zpR
    LDA #>53286
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_shared_colors_v_c3
    STA __zpR
    LDA __fn_sprite_shared_colors_v_c3+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_expand ---------------------------------------------
__fn_sprite_expand_frame:
__fn_sprite_expand_v_n:
    .fill 2, 0
__fn_sprite_expand_v_x_on:
    .fill 2, 0
__fn_sprite_expand_v_y_on:
    .fill 2, 0
__fn_sprite_expand_v_mask:
    .fill 2, 0
__fn_sprite_expand_v_v:
    .fill 2, 0
__fn_sprite_expand_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_expand_pushfr_loop:
    LDA __fn_sprite_expand_frame,Y
    STA (__zpAP),Y
    INY
    CPY #10
    BNE __fn_sprite_expand_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #10
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_expand_popframe:
    SEC
    LDA __rt_csp
    SBC #10
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_expand_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_expand_frame,Y
    INY
    CPY #10
    BNE __fn_sprite_expand_popfr_loop
    RTS
 
__fn_sprite_expand:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_n
    STA __zpR
    LDA __fn_sprite_expand_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    STA __fn_sprite_expand_v_mask
    LDA __zpR+1
    STA __fn_sprite_expand_v_mask+1
    LDA #<53277
    STA __zpR
    LDA #>53277
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
    LDA __fn_sprite_expand_v_x_on
    STA __zpR
    LDA __fn_sprite_expand_v_x_on+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L15
    JMP __L13
__L15:
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_mask
    STA __zpR
    LDA __fn_sprite_expand_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
    JMP __L14
__L13:
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_mask
    STA __zpR
    LDA __fn_sprite_expand_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
__L14:
    LDA #<53277
    STA __zpR
    LDA #>53277
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<53271
    STA __zpR
    LDA #>53271
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
    LDA __fn_sprite_expand_v_y_on
    STA __zpR
    LDA __fn_sprite_expand_v_y_on+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L18
    JMP __L16
__L18:
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_mask
    STA __zpR
    LDA __fn_sprite_expand_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
    JMP __L17
__L16:
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_mask
    STA __zpR
    LDA __fn_sprite_expand_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
__L17:
    LDA #<53271
    STA __zpR
    LDA #>53271
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_priority ---------------------------------------------
__fn_sprite_priority_frame:
__fn_sprite_priority_v_n:
    .fill 2, 0
__fn_sprite_priority_v_behind:
    .fill 2, 0
__fn_sprite_priority_v_mask:
    .fill 2, 0
__fn_sprite_priority_v_v:
    .fill 2, 0
__fn_sprite_priority_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_priority_pushfr_loop:
    LDA __fn_sprite_priority_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sprite_priority_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_priority_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_priority_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_priority_frame,Y
    INY
    CPY #8
    BNE __fn_sprite_priority_popfr_loop
    RTS
 
__fn_sprite_priority:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_priority_v_n
    STA __zpR
    LDA __fn_sprite_priority_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    STA __fn_sprite_priority_v_mask
    LDA __zpR+1
    STA __fn_sprite_priority_v_mask+1
    LDA #<53275
    STA __zpR
    LDA #>53275
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_priority_v_v
    LDA __zpR+1
    STA __fn_sprite_priority_v_v+1
    LDA __fn_sprite_priority_v_behind
    STA __zpR
    LDA __fn_sprite_priority_v_behind+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L21
    JMP __L19
__L21:
    LDA __fn_sprite_priority_v_v
    STA __zpR
    LDA __fn_sprite_priority_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_priority_v_mask
    STA __zpR
    LDA __fn_sprite_priority_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_priority_v_v
    LDA __zpR+1
    STA __fn_sprite_priority_v_v+1
    JMP __L20
__L19:
    LDA __fn_sprite_priority_v_v
    STA __zpR
    LDA __fn_sprite_priority_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_priority_v_mask
    STA __zpR
    LDA __fn_sprite_priority_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_priority_v_v
    LDA __zpR+1
    STA __fn_sprite_priority_v_v+1
__L20:
    LDA #<53275
    STA __zpR
    LDA #>53275
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_priority_v_v
    STA __zpR
    LDA __fn_sprite_priority_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function print_int ---------------------------------------------
__fn_print_int_frame:
__fn_print_int_v_n:
    .fill 2, 0
__fn_print_int_v_buf:
    .fill 6, 0
__fn_print_int_v_i:
    .fill 2, 0
__fn_print_int_v_neg:
    .fill 2, 0
__fn_print_int_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_int_pushfr_loop:
    LDA __fn_print_int_frame,Y
    STA (__zpAP),Y
    INY
    CPY #12
    BNE __fn_print_int_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #12
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_int_popframe:
    SEC
    LDA __rt_csp
    SBC #12
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_int_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_int_frame,Y
    INY
    CPY #12
    BNE __fn_print_int_popfr_loop
    RTS
 
__fn_print_int:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_neg
    LDA __zpR+1
    STA __fn_print_int_v_neg+1
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L24
    JMP __L22
__L24:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_neg
    LDA __zpR+1
    STA __fn_print_int_v_neg+1
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JMP __L23
__L22:
__L23:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L27
    JMP __L25
__L27:
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
    JMP __L26
__L25:
__L26:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
__L28:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L30
    JMP __L29
__L30:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_int_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_int_v_buf
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
    JMP __L28
__L29:
    LDA __fn_print_int_v_neg
    STA __zpR
    LDA __fn_print_int_v_neg+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L33
    JMP __L31
__L33:
    LDA #<45
    STA __zpR
    LDA #>45
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L32
__L31:
__L32:
__L34:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L36
    JMP __L35
__L36:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_int_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_int_v_buf
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L34
__L35:
    RTS
 
; ---- function print_uint ---------------------------------------------
__fn_print_uint_frame:
__fn_print_uint_v_n:
    .fill 2, 0
__fn_print_uint_v_buf:
    .fill 6, 0
__fn_print_uint_v_i:
    .fill 2, 0
__fn_print_uint_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_uint_pushfr_loop:
    LDA __fn_print_uint_frame,Y
    STA (__zpAP),Y
    INY
    CPY #10
    BNE __fn_print_uint_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #10
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_uint_popframe:
    SEC
    LDA __rt_csp
    SBC #10
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_uint_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_uint_frame,Y
    INY
    CPY #10
    BNE __fn_print_uint_popfr_loop
    RTS
 
__fn_print_uint:
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L39
    JMP __L37
__L39:
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
    JMP __L38
__L37:
__L38:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
__L40:
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ugt16
    LDA __zpR
    ORA __zpR+1
    BNE __L42
    JMP __L41
__L42:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_uint_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_uint_v_buf
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_udiv16
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_udiv16
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_n
    LDA __zpR+1
    STA __fn_print_uint_v_n+1
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
    JMP __L40
__L41:
__L43:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L45
    JMP __L44
__L45:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_uint_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_uint_v_buf
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L43
__L44:
    RTS
 
; ---- function print_hex ---------------------------------------------
__fn_print_hex_frame:
__fn_print_hex_v_n:
    .fill 2, 0
__fn_print_hex_v_i:
    .fill 2, 0
__fn_print_hex_v_shift:
    .fill 2, 0
__fn_print_hex_v_digit:
    .fill 2, 0
__fn_print_hex_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_hex_pushfr_loop:
    LDA __fn_print_hex_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_print_hex_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_hex_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_hex_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_hex_frame,Y
    INY
    CPY #8
    BNE __fn_print_hex_popfr_loop
    RTS
 
__fn_print_hex:
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_i
    LDA __zpR+1
    STA __fn_print_hex_v_i+1
__L46:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ge16
    LDA __zpR
    ORA __zpR+1
    BNE __L49
    JMP __L47
__L49:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    LDA __zpR
    STA __fn_print_hex_v_shift
    LDA __zpR+1
    STA __fn_print_hex_v_shift+1
    LDA __fn_print_hex_v_n
    STA __zpR
    LDA __fn_print_hex_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_print_hex_v_shift
    STA __zpR
    LDA __fn_print_hex_v_shift+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shr16
    JSR __rt_push
    LDA #<15
    STA __zpR
    LDA #>15
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_digit
    LDA __zpR+1
    STA __fn_print_hex_v_digit+1
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L52
    JMP __L50
__L52:
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L51
__L50:
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    JSR __rt_push
    LDA #<65
    STA __zpR
    LDA #>65
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
__L51:
__L48:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_hex_v_i
    LDA __zpR+1
    STA __fn_print_hex_v_i+1
    JMP __L46
__L47:
    RTS
 
; ---- function newline ---------------------------------------------
__fn_newline_frame:
__fn_newline_pushframe:
    RTS
 
__fn_newline_popframe:
    RTS
 
__fn_newline:
    LDA #<13
    STA __zpR
    LDA #>13
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
 
; ---- function main ---------------------------------------------
__fn_main_frame:
__fn_main_pushframe:
    RTS
 
__fn_main_popframe:
    RTS
 
__fn_main:
    JSR __fn_border_color_pushframe
    LDA #<6
    STA __zpR
    LDA #>6
    STA __zpR+1
    LDA __zpR
    STA __fn_border_color_v_c
    LDA __zpR+1
    STA __fn_border_color_v_c+1
    JSR __fn_border_color
    JSR __fn_border_color_popframe
    JSR __fn_print_int_pushframe
    LDA #<53280
    STA __zpR
    LDA #>53280
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_background_color_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_background_color_v_c
    LDA __zpR+1
    STA __fn_background_color_v_c+1
    JSR __fn_background_color
    JSR __fn_background_color_popframe
    JSR __fn_print_int_pushframe
    LDA #<53281
    STA __zpR
    LDA #>53281
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_plot_char_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_x
    LDA __zpR+1
    STA __fn_plot_char_v_x+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_y
    LDA __zpR+1
    STA __fn_plot_char_v_y+1
    LDA #<65
    STA __zpR
    LDA #>65
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_screen_code
    LDA __zpR+1
    STA __fn_plot_char_v_screen_code+1
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_color
    LDA __zpR+1
    STA __fn_plot_char_v_color+1
    JSR __fn_plot_char
    JSR __fn_plot_char_popframe
    JSR __fn_print_int_pushframe
    LDA #<1024
    STA __zpR
    LDA #>1024
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<55296
    STA __zpR
    LDA #>55296
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_plot_char_pushframe
    LDA #<39
    STA __zpR
    LDA #>39
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_x
    LDA __zpR+1
    STA __fn_plot_char_v_x+1
    LDA #<24
    STA __zpR
    LDA #>24
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_y
    LDA __zpR+1
    STA __fn_plot_char_v_y+1
    LDA #<90
    STA __zpR
    LDA #>90
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_screen_code
    LDA __zpR+1
    STA __fn_plot_char_v_screen_code+1
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_color
    LDA __zpR+1
    STA __fn_plot_char_v_color+1
    JSR __fn_plot_char
    JSR __fn_plot_char_popframe
    JSR __fn_print_int_pushframe
    LDA #<1024
    STA __zpR
    LDA #>1024
    STA __zpR+1
    JSR __rt_push
    LDA #<24
    STA __zpR
    LDA #>24
    STA __zpR+1
    JSR __rt_push
    LDA #<40
    STA __zpR
    LDA #>40
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<39
    STA __zpR
    LDA #>39
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<55296
    STA __zpR
    LDA #>55296
    STA __zpR+1
    JSR __rt_push
    LDA #<24
    STA __zpR
    LDA #>24
    STA __zpR+1
    JSR __rt_push
    LDA #<40
    STA __zpR
    LDA #>40
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<39
    STA __zpR
    LDA #>39
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_clear_screen_pushframe
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_clear_screen_v_color
    LDA __zpR+1
    STA __fn_clear_screen_v_color+1
    JSR __fn_clear_screen
    JSR __fn_clear_screen_popframe
    JSR __fn_print_int_pushframe
    LDA #<1024
    STA __zpR
    LDA #>1024
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<1024
    STA __zpR
    LDA #>1024
    STA __zpR+1
    JSR __rt_push
    LDA #<999
    STA __zpR
    LDA #>999
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<55296
    STA __zpR
    LDA #>55296
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<55296
    STA __zpR
    LDA #>55296
    STA __zpR+1
    JSR __rt_push
    LDA #<999
    STA __zpR
    LDA #>999
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_enable_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_n
    LDA __zpR+1
    STA __fn_sprite_enable_v_n+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_on
    LDA __zpR+1
    STA __fn_sprite_enable_v_on+1
    JSR __fn_sprite_enable
    JSR __fn_sprite_enable_popframe
    JSR __fn_print_int_pushframe
    LDA #<53269
    STA __zpR
    LDA #>53269
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_enable_pushframe
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_n
    LDA __zpR+1
    STA __fn_sprite_enable_v_n+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_on
    LDA __zpR+1
    STA __fn_sprite_enable_v_on+1
    JSR __fn_sprite_enable
    JSR __fn_sprite_enable_popframe
    JSR __fn_print_int_pushframe
    LDA #<53269
    STA __zpR
    LDA #>53269
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_enable_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_n
    LDA __zpR+1
    STA __fn_sprite_enable_v_n+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_on
    LDA __zpR+1
    STA __fn_sprite_enable_v_on+1
    JSR __fn_sprite_enable
    JSR __fn_sprite_enable_popframe
    JSR __fn_print_int_pushframe
    LDA #<53269
    STA __zpR
    LDA #>53269
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_pos_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_n
    LDA __zpR+1
    STA __fn_sprite_pos_v_n+1
    LDA #<100
    STA __zpR
    LDA #>100
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_x
    LDA __zpR+1
    STA __fn_sprite_pos_v_x+1
    LDA #<50
    STA __zpR
    LDA #>50
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_y
    LDA __zpR+1
    STA __fn_sprite_pos_v_y+1
    JSR __fn_sprite_pos
    JSR __fn_sprite_pos_popframe
    JSR __fn_print_int_pushframe
    LDA #<53248
    STA __zpR
    LDA #>53248
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<53249
    STA __zpR
    LDA #>53249
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<53264
    STA __zpR
    LDA #>53264
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_pos_pushframe
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_n
    LDA __zpR+1
    STA __fn_sprite_pos_v_n+1
    LDA #<300
    STA __zpR
    LDA #>300
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_x
    LDA __zpR+1
    STA __fn_sprite_pos_v_x+1
    LDA #<60
    STA __zpR
    LDA #>60
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_y
    LDA __zpR+1
    STA __fn_sprite_pos_v_y+1
    JSR __fn_sprite_pos
    JSR __fn_sprite_pos_popframe
    JSR __fn_print_int_pushframe
    LDA #<53250
    STA __zpR
    LDA #>53250
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<53251
    STA __zpR
    LDA #>53251
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<53264
    STA __zpR
    LDA #>53264
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_color_pushframe
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_color_v_n
    LDA __zpR+1
    STA __fn_sprite_color_v_n+1
    LDA #<9
    STA __zpR
    LDA #>9
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_color_v_c
    LDA __zpR+1
    STA __fn_sprite_color_v_c+1
    JSR __fn_sprite_color
    JSR __fn_sprite_color_popframe
    JSR __fn_print_int_pushframe
    LDA #<53290
    STA __zpR
    LDA #>53290
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_pointer_pushframe
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pointer_v_n
    LDA __zpR+1
    STA __fn_sprite_pointer_v_n+1
    LDA #<13
    STA __zpR
    LDA #>13
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pointer_v_block
    LDA __zpR+1
    STA __fn_sprite_pointer_v_block+1
    JSR __fn_sprite_pointer
    JSR __fn_sprite_pointer_popframe
    JSR __fn_print_int_pushframe
    LDA #<2045
    STA __zpR
    LDA #>2045
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_multicolor_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_multicolor_v_n
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_n+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_multicolor_v_on
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_on+1
    JSR __fn_sprite_multicolor
    JSR __fn_sprite_multicolor_popframe
    JSR __fn_print_int_pushframe
    LDA #<53276
    STA __zpR
    LDA #>53276
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_shared_colors_pushframe
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_shared_colors_v_c1
    LDA __zpR+1
    STA __fn_sprite_shared_colors_v_c1+1
    LDA #<8
    STA __zpR
    LDA #>8
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_shared_colors_v_c3
    LDA __zpR+1
    STA __fn_sprite_shared_colors_v_c3+1
    JSR __fn_sprite_shared_colors
    JSR __fn_sprite_shared_colors_popframe
    JSR __fn_print_int_pushframe
    LDA #<53285
    STA __zpR
    LDA #>53285
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<53286
    STA __zpR
    LDA #>53286
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_expand_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_n
    LDA __zpR+1
    STA __fn_sprite_expand_v_n+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_x_on
    LDA __zpR+1
    STA __fn_sprite_expand_v_x_on+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_y_on
    LDA __zpR+1
    STA __fn_sprite_expand_v_y_on+1
    JSR __fn_sprite_expand
    JSR __fn_sprite_expand_popframe
    JSR __fn_print_int_pushframe
    LDA #<53277
    STA __zpR
    LDA #>53277
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<53271
    STA __zpR
    LDA #>53271
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_sprite_priority_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_priority_v_n
    LDA __zpR+1
    STA __fn_sprite_priority_v_n+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_priority_v_behind
    LDA __zpR+1
    STA __fn_sprite_priority_v_behind+1
    JSR __fn_sprite_priority
    JSR __fn_sprite_priority_popframe
    JSR __fn_print_int_pushframe
    LDA #<53275
    STA __zpR
    LDA #>53275
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<__str_2
    STA __zpR
    LDA #>__str_2
    STA __zpR+1
    JSR __rt_puts
    RTS
 
; ---- string literals (raw bytes; __rt_puts converts at print time) ----
__str_0:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,67,65,76,76,32,83,84,65,67,75,32
    .byte 79,86,69,82,70,76,79,87,13,40,82,69,67,85,82,83,73,79,78,32,84,79,79,32,68,69,69,80,44,32,79,82
    .byte 32,77,73,83,83,73,78,71,32,66,65,83,69,32,67,65,83,69,41,13,0
__str_1:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,69,88,80,82,69,83,83,73,79,78,32
    .byte 83,84,65,67,75,32,79,86,69,82,70,76,79,87,13,40,69,88,80,82,69,83,83,73,79,78,83,32,78,69,83,84
    .byte 69,68,32,84,79,79,32,68,69,69,80,76,89,32,65,67,82,79,83,83,32,82,69,67,85,82,83,73,79,78,41,13
    .byte 0
__str_2:
    .byte 68,79,78,69,46,0
 
; ---- operand stack (128 16-bit slots, indexed by __rt_spidx) -------
__rt_stack:
    .fill 256, 0
; ---- call stack (4096 bytes; see codegen_stmt.c's emit_function() ---
; ---- and codegen_runtime.c's cstack-check comment for what this is)--
__rt_cstack:
    .fill 4096, 0
