; Generated by cc64 from ./tests/include.c
; Assemble with: c64asm ./tests/include.asm -o program.prg
 
; ---- zero page pseudo-registers ---------------------------------
; Only $02/$03 and $FB-$FE are used here. Per the KERNAL's own
; memory map, those are the ONLY zero-page bytes confirmed genuinely
; free: $F3/$F4 is the current-line-in-color-RAM pointer (touched by
; CHROUT itself when it colors a printed character) and $F5/$F6 is the
; keyboard-matrix-to-PETSCII conversion table pointer (touched by the
; keyboard scan on every background IRQ, ~60x/sec) - both looked like
; safe 'adjacent' bytes but are not; this bit us for real once already.
__zpAP = $02      ; effective-address pointer (2 bytes) - needs zero
                  ; page because it's used with (zp),Y indirection
__zpR  = $FB      ; primary register / return value (2 bytes)
__zpR2 = $FD      ; secondary operand register (2 bytes)
__CHROUT = $FFD2
 
.basic
    LDA #14           ; switch to the lower/upper character set - required
    JSR __CHROUT      ; for the PETSCII case mapping below to render as letters
                      ; (the default charset only has graphics past $C0)
    LDA #0
    STA __rt_spidx
    LDA #<__rt_cstack ; call-stack pointer starts at the base of its buffer -
    STA __rt_csp      ; see codegen_stmt.c's emit_function() for how each
    LDA #>__rt_cstack ; function's push/popframe routines use it to support
    STA __rt_csp+1    ; recursion despite locals/params living at fixed addresses
    JSR __fn_main
    RTS
 
; ---- runtime scratch storage (plain RAM, NOT zero page - only __zpAP
; needs (zp),Y indirection; these are always accessed directly) -------
__rt_spidx:
    .byte 0
__rt_csp:
    .fill 2, 0
__zpT1:
    .fill 2, 0
__zpT0:
    .fill 2, 0
 
; ---- runtime library -------------------------------------------
__rt_push:
    LDX __rt_spidx
    LDA __zpR
    STA __rt_stack,X
    LDA __zpR+1
    STA __rt_stack+1,X
    INX
    INX
    STX __rt_spidx
    BNE __rt_push_ok
    LDA #<__str_1
    STA __zpR
    LDA #>__str_1
    STA __zpR+1
    JSR __rt_puts
__rt_push_halt:
    JMP __rt_push_halt
__rt_push_ok:
    RTS
 
__rt_pop2:
    LDX __rt_spidx
    DEX
    DEX
    LDA __rt_stack,X
    STA __zpR2
    LDA __rt_stack+1,X
    STA __zpR2+1
    STX __rt_spidx
    RTS
 
__rt_cstack_check:
    TSX
    CPX #$20
    BCC __rt_csc_overflow
    LDA __rt_csp+1
    CMP #>(__rt_cstack+4096)
    BCC __rt_csc_ok
    BNE __rt_csc_overflow
    LDA __rt_csp
    CMP #<(__rt_cstack+4096)
    BCC __rt_csc_ok
    BEQ __rt_csc_ok
__rt_csc_overflow:
    LDA #<__str_0
    STA __zpR
    LDA #>__str_0
    STA __zpR+1
    JSR __rt_puts
__rt_csc_halt:
    JMP __rt_csc_halt
__rt_csc_ok:
    RTS
 
__rt_mul16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_mul16_loop:
    LSR __zpR+1
    ROR __zpR
    BCC __rt_mul16_noadd
    CLC
    LDA __zpT0
    ADC __zpR2
    STA __zpT0
    LDA __zpT0+1
    ADC __zpR2+1
    STA __zpT0+1
__rt_mul16_noadd:
    ASL __zpR2
    ROL __zpR2+1
    DEX
    BNE __rt_mul16_loop
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    RTS
 
__rt_udiv16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_udiv16_loop:
    ASL __zpR2
    ROL __zpR2+1
    ROL __zpT0
    ROL __zpT0+1
    LDA __zpT0
    SEC
    SBC __zpR
    TAY
    LDA __zpT0+1
    SBC __zpR+1
    BCC __rt_udiv16_skip
    STA __zpT0+1
    STY __zpT0
    INC __zpR2
__rt_udiv16_skip:
    DEX
    BNE __rt_udiv16_loop
    RTS
 
__rt_neg_r2:
    SEC
    LDA #0
    SBC __zpR2
    TAX
    LDA #0
    SBC __zpR2+1
    STA __zpR2+1
    STX __zpR2
    RTS
 
__rt_neg_r:
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    RTS
 
__rt_neg_t0:
    SEC
    LDA #0
    SBC __zpT0
    TAX
    LDA #0
    SBC __zpT0+1
    STA __zpT0+1
    STX __zpT0
    RTS
 
__rt_sdivmod16:
    LDA #0
    STA __zpT1
    STA __zpT1+1
    LDA __zpR2+1
    BPL __rt_sdm_d1
    JSR __rt_neg_r2
    INC __zpT1
__rt_sdm_d1:
    LDA __zpR+1
    BPL __rt_sdm_d2
    JSR __rt_neg_r
    INC __zpT1+1
__rt_sdm_d2:
    JSR __rt_udiv16
    LDA __zpT1
    EOR __zpT1+1
    AND #1
    BEQ __rt_sdm_qdone
    JSR __rt_neg_r2
__rt_sdm_qdone:
    LDA __zpT1
    BEQ __rt_sdm_rdone
    JSR __rt_neg_t0
__rt_sdm_rdone:
    RTS
 
__rt_eq16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_eq16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_eq16_ne
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_eq16_ne:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_ne16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_ne16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_ne16_ne
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ne16_ne:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_sub_r2r:
    SEC
    LDA __zpR2
    SBC __zpR
    LDA __zpR2+1
    SBC __zpR+1
    BVC __rt_sub_r2r_ok
    EOR #$80
__rt_sub_r2r_ok:
    RTS
 
__rt_sub_rr2:
    SEC
    LDA __zpR
    SBC __zpR2
    LDA __zpR+1
    SBC __zpR2+1
    BVC __rt_sub_rr2_ok
    EOR #$80
__rt_sub_rr2_ok:
    RTS
 
__rt_lt16:
    JSR __rt_sub_r2r
    BMI __rt_lt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_lt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ge16:
    JSR __rt_sub_r2r
    BPL __rt_ge16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_gt16:
    JSR __rt_sub_rr2
    BMI __rt_gt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_gt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_le16:
    JSR __rt_sub_rr2
    BPL __rt_le16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_le16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_shl16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shl16_loop:
    CPX #0
    BEQ __rt_shl16_done
    ASL __zpR
    ROL __zpR+1
    DEX
    JMP __rt_shl16_loop
__rt_shl16_done:
    RTS
 
__rt_shr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shr16_loop:
    CPX #0
    BEQ __rt_shr16_done
    LDA __zpR+1
    CMP #$80
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_shr16_loop
__rt_shr16_done:
    RTS
 
__rt_topetscii:
    LDA __zpR
    CMP #$61
    BCC __rt_tp_notlower
    CMP #$7B
    BCS __rt_tp_notlower
    SEC
    SBC #$20
    STA __zpR
    JMP __rt_tp_done
__rt_tp_notlower:
    CMP #$41
    BCC __rt_tp_done
    CMP #$5B
    BCS __rt_tp_done
    CLC
    ADC #$80
    STA __zpR
__rt_tp_done:
    RTS
 
__rt_ult16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_ult16_t
    BNE __rt_ult16_f
    LDA __zpR2
    CMP __zpR
    BCC __rt_ult16_t
__rt_ult16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ult16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ugt16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ugt16_t
    BNE __rt_ugt16_f
    LDA __zpR
    CMP __zpR2
    BCC __rt_ugt16_t
__rt_ugt16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ugt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ule16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ule16_f
    BNE __rt_ule16_t
    LDA __zpR
    CMP __zpR2
    BCC __rt_ule16_f
__rt_ule16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_ule16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_uge16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_uge16_f
    BNE __rt_uge16_t
    LDA __zpR2
    CMP __zpR
    BCC __rt_uge16_f
__rt_uge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_uge16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_puts:
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
__rt_puts_loop:
    LDY #0
    LDA (__zpAP),Y
    BEQ __rt_puts_done
    STA __zpR
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    CLC
    LDA __zpAP
    ADC #1
    STA __zpAP
    LDA __zpAP+1
    ADC #0
    STA __zpAP+1
    JMP __rt_puts_loop
__rt_puts_done:
    RTS
 
; ---- global variables --------------------------------------------
__g_buf:
    .fill 32, 0
__g_buf2:
    .fill 32, 0
 
; ---- function strlen ---------------------------------------------
__fn_strlen_frame:
__fn_strlen_v_s:
    .fill 2, 0
__fn_strlen_v_n:
    .fill 2, 0
__fn_strlen_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strlen_pushfr_loop:
    LDA __fn_strlen_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_strlen_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_strlen_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strlen_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_strlen_frame,Y
    INY
    CPY #4
    BNE __fn_strlen_popfr_loop
    RTS
 
__fn_strlen:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_strlen_v_n
    LDA __zpR+1
    STA __fn_strlen_v_n+1
__L0:
    LDA __fn_strlen_v_s
    STA __zpR
    LDA __fn_strlen_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L2
    JMP __L1
__L2:
    LDA __fn_strlen_v_n
    STA __zpR
    LDA __fn_strlen_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strlen_v_n
    LDA __zpR+1
    STA __fn_strlen_v_n+1
    LDA __fn_strlen_v_s
    STA __zpR
    LDA __fn_strlen_v_s+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strlen_v_s
    LDA __zpR+1
    STA __fn_strlen_v_s+1
    JMP __L0
__L1:
    LDA __fn_strlen_v_n
    STA __zpR
    LDA __fn_strlen_v_n+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function strcpy ---------------------------------------------
__fn_strcpy_frame:
__fn_strcpy_v_dst:
    .fill 2, 0
__fn_strcpy_v_src:
    .fill 2, 0
__fn_strcpy_v_d:
    .fill 2, 0
__fn_strcpy_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strcpy_pushfr_loop:
    LDA __fn_strcpy_frame,Y
    STA (__zpAP),Y
    INY
    CPY #6
    BNE __fn_strcpy_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #6
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_strcpy_popframe:
    SEC
    LDA __rt_csp
    SBC #6
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strcpy_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_strcpy_frame,Y
    INY
    CPY #6
    BNE __fn_strcpy_popfr_loop
    RTS
 
__fn_strcpy:
    LDA __fn_strcpy_v_dst
    STA __zpR
    LDA __fn_strcpy_v_dst+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcpy_v_d
    LDA __zpR+1
    STA __fn_strcpy_v_d+1
__L3:
    LDA __fn_strcpy_v_src
    STA __zpR
    LDA __fn_strcpy_v_src+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L5
    JMP __L4
__L5:
    LDA __fn_strcpy_v_d
    STA __zpR
    LDA __fn_strcpy_v_d+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_strcpy_v_src
    STA __zpR
    LDA __fn_strcpy_v_src+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_strcpy_v_d
    STA __zpR
    LDA __fn_strcpy_v_d+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcpy_v_d
    LDA __zpR+1
    STA __fn_strcpy_v_d+1
    LDA __fn_strcpy_v_src
    STA __zpR
    LDA __fn_strcpy_v_src+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcpy_v_src
    LDA __zpR+1
    STA __fn_strcpy_v_src+1
    JMP __L3
__L4:
    LDA __fn_strcpy_v_d
    STA __zpR
    LDA __fn_strcpy_v_d+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_strcpy_v_dst
    STA __zpR
    LDA __fn_strcpy_v_dst+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function strcat ---------------------------------------------
__fn_strcat_frame:
__fn_strcat_v_dst:
    .fill 2, 0
__fn_strcat_v_src:
    .fill 2, 0
__fn_strcat_v_d:
    .fill 2, 0
__fn_strcat_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strcat_pushfr_loop:
    LDA __fn_strcat_frame,Y
    STA (__zpAP),Y
    INY
    CPY #6
    BNE __fn_strcat_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #6
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_strcat_popframe:
    SEC
    LDA __rt_csp
    SBC #6
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strcat_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_strcat_frame,Y
    INY
    CPY #6
    BNE __fn_strcat_popfr_loop
    RTS
 
__fn_strcat:
    LDA __fn_strcat_v_dst
    STA __zpR
    LDA __fn_strcat_v_dst+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcat_v_d
    LDA __zpR+1
    STA __fn_strcat_v_d+1
__L6:
    LDA __fn_strcat_v_d
    STA __zpR
    LDA __fn_strcat_v_d+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L8
    JMP __L7
__L8:
    LDA __fn_strcat_v_d
    STA __zpR
    LDA __fn_strcat_v_d+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcat_v_d
    LDA __zpR+1
    STA __fn_strcat_v_d+1
    JMP __L6
__L7:
__L9:
    LDA __fn_strcat_v_src
    STA __zpR
    LDA __fn_strcat_v_src+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L11
    JMP __L10
__L11:
    LDA __fn_strcat_v_d
    STA __zpR
    LDA __fn_strcat_v_d+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_strcat_v_src
    STA __zpR
    LDA __fn_strcat_v_src+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_strcat_v_d
    STA __zpR
    LDA __fn_strcat_v_d+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcat_v_d
    LDA __zpR+1
    STA __fn_strcat_v_d+1
    LDA __fn_strcat_v_src
    STA __zpR
    LDA __fn_strcat_v_src+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcat_v_src
    LDA __zpR+1
    STA __fn_strcat_v_src+1
    JMP __L9
__L10:
    LDA __fn_strcat_v_d
    STA __zpR
    LDA __fn_strcat_v_d+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_strcat_v_dst
    STA __zpR
    LDA __fn_strcat_v_dst+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function strcmp ---------------------------------------------
__fn_strcmp_frame:
__fn_strcmp_v_a:
    .fill 2, 0
__fn_strcmp_v_b:
    .fill 2, 0
__fn_strcmp_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strcmp_pushfr_loop:
    LDA __fn_strcmp_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_strcmp_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_strcmp_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strcmp_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_strcmp_frame,Y
    INY
    CPY #4
    BNE __fn_strcmp_popfr_loop
    RTS
 
__fn_strcmp:
__L12:
    LDA __fn_strcmp_v_a
    STA __zpR
    LDA __fn_strcmp_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L16
    JMP __L14
__L16:
    LDA __fn_strcmp_v_a
    STA __zpR
    LDA __fn_strcmp_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA __fn_strcmp_v_b
    STA __zpR
    LDA __fn_strcmp_v_b+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L17
    JMP __L14
__L17:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    JMP __L15
__L14:
    LDA #0
    STA __zpR
    STA __zpR+1
__L15:
    LDA __zpR
    ORA __zpR+1
    BNE __L18
    JMP __L13
__L18:
    LDA __fn_strcmp_v_a
    STA __zpR
    LDA __fn_strcmp_v_a+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_a
    LDA __zpR+1
    STA __fn_strcmp_v_a+1
    LDA __fn_strcmp_v_b
    STA __zpR
    LDA __fn_strcmp_v_b+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_b
    LDA __zpR+1
    STA __fn_strcmp_v_b+1
    JMP __L12
__L13:
    LDA __fn_strcmp_v_a
    STA __zpR
    LDA __fn_strcmp_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA __fn_strcmp_v_b
    STA __zpR
    LDA __fn_strcmp_v_b+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    RTS
    RTS
 
; ---- function strchr ---------------------------------------------
__fn_strchr_frame:
__fn_strchr_v_s:
    .fill 2, 0
__fn_strchr_v_c:
    .fill 2, 0
__fn_strchr_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strchr_pushfr_loop:
    LDA __fn_strchr_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_strchr_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_strchr_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_strchr_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_strchr_frame,Y
    INY
    CPY #4
    BNE __fn_strchr_popfr_loop
    RTS
 
__fn_strchr:
__L19:
    LDA __fn_strchr_v_s
    STA __zpR
    LDA __fn_strchr_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L21
    JMP __L20
__L21:
    LDA __fn_strchr_v_s
    STA __zpR
    LDA __fn_strchr_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA __fn_strchr_v_c
    STA __zpR
    LDA __fn_strchr_v_c+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L24
    JMP __L22
__L24:
    LDA __fn_strchr_v_s
    STA __zpR
    LDA __fn_strchr_v_s+1
    STA __zpR+1
    RTS
    JMP __L23
__L22:
__L23:
    LDA __fn_strchr_v_s
    STA __zpR
    LDA __fn_strchr_v_s+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_strchr_v_s
    LDA __zpR+1
    STA __fn_strchr_v_s+1
    JMP __L19
__L20:
    LDA __fn_strchr_v_c
    STA __zpR
    LDA __fn_strchr_v_c+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L27
    JMP __L25
__L27:
    LDA __fn_strchr_v_s
    STA __zpR
    LDA __fn_strchr_v_s+1
    STA __zpR+1
    RTS
    JMP __L26
__L25:
__L26:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    RTS
    RTS
 
; ---- function memset ---------------------------------------------
__fn_memset_frame:
__fn_memset_v_dst:
    .fill 2, 0
__fn_memset_v_val:
    .fill 2, 0
__fn_memset_v_n:
    .fill 2, 0
__fn_memset_v_i:
    .fill 2, 0
__fn_memset_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_memset_pushfr_loop:
    LDA __fn_memset_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_memset_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_memset_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_memset_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_memset_frame,Y
    INY
    CPY #8
    BNE __fn_memset_popfr_loop
    RTS
 
__fn_memset:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_memset_v_i
    LDA __zpR+1
    STA __fn_memset_v_i+1
__L28:
    LDA __fn_memset_v_i
    STA __zpR
    LDA __fn_memset_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_memset_v_n
    STA __zpR
    LDA __fn_memset_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L31
    JMP __L29
__L31:
    LDA __fn_memset_v_dst
    STA __zpR
    LDA __fn_memset_v_dst+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_memset_v_i
    STA __zpR
    LDA __fn_memset_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpAP
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_memset_v_val
    STA __zpR
    LDA __fn_memset_v_val+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
__L30:
    LDA __fn_memset_v_i
    STA __zpR
    LDA __fn_memset_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_memset_v_i
    LDA __zpR+1
    STA __fn_memset_v_i+1
    JMP __L28
__L29:
    LDA __fn_memset_v_dst
    STA __zpR
    LDA __fn_memset_v_dst+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function memcpy ---------------------------------------------
__fn_memcpy_frame:
__fn_memcpy_v_dst:
    .fill 2, 0
__fn_memcpy_v_src:
    .fill 2, 0
__fn_memcpy_v_n:
    .fill 2, 0
__fn_memcpy_v_i:
    .fill 2, 0
__fn_memcpy_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_memcpy_pushfr_loop:
    LDA __fn_memcpy_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_memcpy_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_memcpy_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_memcpy_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_memcpy_frame,Y
    INY
    CPY #8
    BNE __fn_memcpy_popfr_loop
    RTS
 
__fn_memcpy:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_memcpy_v_i
    LDA __zpR+1
    STA __fn_memcpy_v_i+1
__L32:
    LDA __fn_memcpy_v_i
    STA __zpR
    LDA __fn_memcpy_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_memcpy_v_n
    STA __zpR
    LDA __fn_memcpy_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L35
    JMP __L33
__L35:
    LDA __fn_memcpy_v_dst
    STA __zpR
    LDA __fn_memcpy_v_dst+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_memcpy_v_i
    STA __zpR
    LDA __fn_memcpy_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpAP
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_memcpy_v_src
    STA __zpR
    LDA __fn_memcpy_v_src+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_memcpy_v_i
    STA __zpR
    LDA __fn_memcpy_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpAP
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
__L34:
    LDA __fn_memcpy_v_i
    STA __zpR
    LDA __fn_memcpy_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_memcpy_v_i
    LDA __zpR+1
    STA __fn_memcpy_v_i+1
    JMP __L32
__L33:
    LDA __fn_memcpy_v_dst
    STA __zpR
    LDA __fn_memcpy_v_dst+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function print_int ---------------------------------------------
__fn_print_int_frame:
__fn_print_int_v_n:
    .fill 2, 0
__fn_print_int_v_buf:
    .fill 6, 0
__fn_print_int_v_i:
    .fill 2, 0
__fn_print_int_v_neg:
    .fill 2, 0
__fn_print_int_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_int_pushfr_loop:
    LDA __fn_print_int_frame,Y
    STA (__zpAP),Y
    INY
    CPY #12
    BNE __fn_print_int_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #12
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_int_popframe:
    SEC
    LDA __rt_csp
    SBC #12
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_int_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_int_frame,Y
    INY
    CPY #12
    BNE __fn_print_int_popfr_loop
    RTS
 
__fn_print_int:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_neg
    LDA __zpR+1
    STA __fn_print_int_v_neg+1
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L38
    JMP __L36
__L38:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_neg
    LDA __zpR+1
    STA __fn_print_int_v_neg+1
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JMP __L37
__L36:
__L37:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L41
    JMP __L39
__L41:
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
    JMP __L40
__L39:
__L40:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
__L42:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L44
    JMP __L43
__L44:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_int_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_int_v_buf
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
    JMP __L42
__L43:
    LDA __fn_print_int_v_neg
    STA __zpR
    LDA __fn_print_int_v_neg+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L47
    JMP __L45
__L47:
    LDA #<45
    STA __zpR
    LDA #>45
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L46
__L45:
__L46:
__L48:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L50
    JMP __L49
__L50:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_int_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_int_v_buf
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L48
__L49:
    RTS
 
; ---- function print_hex ---------------------------------------------
__fn_print_hex_frame:
__fn_print_hex_v_n:
    .fill 2, 0
__fn_print_hex_v_i:
    .fill 2, 0
__fn_print_hex_v_shift:
    .fill 2, 0
__fn_print_hex_v_digit:
    .fill 2, 0
__fn_print_hex_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_hex_pushfr_loop:
    LDA __fn_print_hex_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_print_hex_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_hex_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_hex_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_hex_frame,Y
    INY
    CPY #8
    BNE __fn_print_hex_popfr_loop
    RTS
 
__fn_print_hex:
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_i
    LDA __zpR+1
    STA __fn_print_hex_v_i+1
__L51:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ge16
    LDA __zpR
    ORA __zpR+1
    BNE __L54
    JMP __L52
__L54:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    LDA __zpR
    STA __fn_print_hex_v_shift
    LDA __zpR+1
    STA __fn_print_hex_v_shift+1
    LDA __fn_print_hex_v_n
    STA __zpR
    LDA __fn_print_hex_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_print_hex_v_shift
    STA __zpR
    LDA __fn_print_hex_v_shift+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shr16
    JSR __rt_push
    LDA #<15
    STA __zpR
    LDA #>15
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_digit
    LDA __zpR+1
    STA __fn_print_hex_v_digit+1
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L57
    JMP __L55
__L57:
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L56
__L55:
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    JSR __rt_push
    LDA #<65
    STA __zpR
    LDA #>65
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
__L56:
__L53:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_hex_v_i
    LDA __zpR+1
    STA __fn_print_hex_v_i+1
    JMP __L51
__L52:
    RTS
 
; ---- function newline ---------------------------------------------
__fn_newline_frame:
__fn_newline_pushframe:
    RTS
 
__fn_newline_popframe:
    RTS
 
__fn_newline:
    LDA #<13
    STA __zpR
    LDA #>13
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
 
; ---- function count_matching ---------------------------------------------
__fn_count_matching_frame:
__fn_count_matching_v_a:
    .fill 2, 0
__fn_count_matching_v_b:
    .fill 2, 0
__fn_count_matching_v_n:
    .fill 2, 0
__fn_count_matching_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_count_matching_pushfr_loop:
    LDA __fn_count_matching_frame,Y
    STA (__zpAP),Y
    INY
    CPY #6
    BNE __fn_count_matching_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #6
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_count_matching_popframe:
    SEC
    LDA __rt_csp
    SBC #6
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_count_matching_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_count_matching_frame,Y
    INY
    CPY #6
    BNE __fn_count_matching_popfr_loop
    RTS
 
__fn_count_matching:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_count_matching_v_n
    LDA __zpR+1
    STA __fn_count_matching_v_n+1
__L58:
    LDA __fn_count_matching_v_a
    STA __zpR
    LDA __fn_count_matching_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L62
    JMP __L60
__L62:
    LDA __fn_count_matching_v_b
    STA __zpR
    LDA __fn_count_matching_v_b+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L63
    JMP __L60
__L63:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    JMP __L61
__L60:
    LDA #0
    STA __zpR
    STA __zpR+1
__L61:
    LDA __zpR
    ORA __zpR+1
    BNE __L64
    JMP __L59
__L64:
    LDA __fn_count_matching_v_a
    STA __zpR
    LDA __fn_count_matching_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA __fn_count_matching_v_b
    STA __zpR
    LDA __fn_count_matching_v_b+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L67
    JMP __L65
__L67:
    LDA __fn_count_matching_v_n
    STA __zpR
    LDA __fn_count_matching_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_count_matching_v_n
    LDA __zpR+1
    STA __fn_count_matching_v_n+1
    JMP __L66
__L65:
__L66:
    LDA __fn_count_matching_v_a
    STA __zpR
    LDA __fn_count_matching_v_a+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_count_matching_v_a
    LDA __zpR+1
    STA __fn_count_matching_v_a+1
    LDA __fn_count_matching_v_b
    STA __zpR
    LDA __fn_count_matching_v_b+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_count_matching_v_b
    LDA __zpR+1
    STA __fn_count_matching_v_b+1
    JMP __L58
__L59:
    LDA __fn_count_matching_v_n
    STA __zpR
    LDA __fn_count_matching_v_n+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function main ---------------------------------------------
__fn_main_frame:
__fn_main_pushframe:
    RTS
 
__fn_main_popframe:
    RTS
 
__fn_main:
    JSR __fn_print_int_pushframe
    JSR __fn_strlen_pushframe
    LDA #<__str_2
    STA __zpR
    LDA #>__str_2
    STA __zpR+1
    LDA __zpR
    STA __fn_strlen_v_s
    LDA __zpR+1
    STA __fn_strlen_v_s+1
    JSR __fn_strlen
    JSR __fn_strlen_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_strlen_pushframe
    LDA #<__str_3
    STA __zpR
    LDA #>__str_3
    STA __zpR+1
    LDA __zpR
    STA __fn_strlen_v_s
    LDA __zpR+1
    STA __fn_strlen_v_s+1
    JSR __fn_strlen
    JSR __fn_strlen_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_strcpy_pushframe
    LDA #<__g_buf
    STA __zpR
    LDA #>__g_buf
    STA __zpR+1
    LDA __zpR
    STA __fn_strcpy_v_dst
    LDA __zpR+1
    STA __fn_strcpy_v_dst+1
    LDA #<__str_4
    STA __zpR
    LDA #>__str_4
    STA __zpR+1
    LDA __zpR
    STA __fn_strcpy_v_src
    LDA __zpR+1
    STA __fn_strcpy_v_src+1
    JSR __fn_strcpy
    JSR __fn_strcpy_popframe
    JSR __fn_strcat_pushframe
    LDA #<__g_buf
    STA __zpR
    LDA #>__g_buf
    STA __zpR+1
    LDA __zpR
    STA __fn_strcat_v_dst
    LDA __zpR+1
    STA __fn_strcat_v_dst+1
    LDA #<__str_5
    STA __zpR
    LDA #>__str_5
    STA __zpR+1
    LDA __zpR
    STA __fn_strcat_v_src
    LDA __zpR+1
    STA __fn_strcat_v_src+1
    JSR __fn_strcat
    JSR __fn_strcat_popframe
    LDA #<__g_buf
    STA __zpR
    LDA #>__g_buf
    STA __zpR+1
    JSR __rt_puts
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_strcpy_pushframe
    LDA #<__g_buf2
    STA __zpR
    LDA #>__g_buf2
    STA __zpR+1
    LDA __zpR
    STA __fn_strcpy_v_dst
    LDA __zpR+1
    STA __fn_strcpy_v_dst+1
    LDA #<__str_6
    STA __zpR
    LDA #>__str_6
    STA __zpR+1
    LDA __zpR
    STA __fn_strcpy_v_src
    LDA __zpR+1
    STA __fn_strcpy_v_src+1
    JSR __fn_strcpy
    JSR __fn_strcpy_popframe
    JSR __rt_puts
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_strcmp_pushframe
    LDA #<__str_7
    STA __zpR
    LDA #>__str_7
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_a
    LDA __zpR+1
    STA __fn_strcmp_v_a+1
    LDA #<__str_8
    STA __zpR
    LDA #>__str_8
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_b
    LDA __zpR+1
    STA __fn_strcmp_v_b+1
    JSR __fn_strcmp
    JSR __fn_strcmp_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_strcmp_pushframe
    LDA #<__str_9
    STA __zpR
    LDA #>__str_9
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_a
    LDA __zpR+1
    STA __fn_strcmp_v_a+1
    LDA #<__str_10
    STA __zpR
    LDA #>__str_10
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_b
    LDA __zpR+1
    STA __fn_strcmp_v_b+1
    JSR __fn_strcmp
    JSR __fn_strcmp_popframe
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_strcmp_pushframe
    LDA #<__str_11
    STA __zpR
    LDA #>__str_11
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_a
    LDA __zpR+1
    STA __fn_strcmp_v_a+1
    LDA #<__str_12
    STA __zpR
    LDA #>__str_12
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_b
    LDA __zpR+1
    STA __fn_strcmp_v_b+1
    JSR __fn_strcmp
    JSR __fn_strcmp_popframe
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_strcmp_pushframe
    LDA #<__str_13
    STA __zpR
    LDA #>__str_13
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_a
    LDA __zpR+1
    STA __fn_strcmp_v_a+1
    LDA #<__str_14
    STA __zpR
    LDA #>__str_14
    STA __zpR+1
    LDA __zpR
    STA __fn_strcmp_v_b
    LDA __zpR+1
    STA __fn_strcmp_v_b+1
    JSR __fn_strcmp
    JSR __fn_strcmp_popframe
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_strchr_pushframe
    LDA #<__str_15
    STA __zpR
    LDA #>__str_15
    STA __zpR+1
    LDA __zpR
    STA __fn_strchr_v_s
    LDA __zpR+1
    STA __fn_strchr_v_s+1
    LDA #<119
    STA __zpR
    LDA #>119
    STA __zpR+1
    LDA __zpR
    STA __fn_strchr_v_c
    LDA __zpR+1
    STA __fn_strchr_v_c+1
    JSR __fn_strchr
    JSR __fn_strchr_popframe
    JSR __rt_puts
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_strchr_pushframe
    LDA #<__str_16
    STA __zpR
    LDA #>__str_16
    STA __zpR+1
    LDA __zpR
    STA __fn_strchr_v_s
    LDA __zpR+1
    STA __fn_strchr_v_s+1
    LDA #<122
    STA __zpR
    LDA #>122
    STA __zpR+1
    LDA __zpR
    STA __fn_strchr_v_c
    LDA __zpR+1
    STA __fn_strchr_v_c+1
    JSR __fn_strchr
    JSR __fn_strchr_popframe
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_memset_pushframe
    LDA #<__g_buf
    STA __zpR
    LDA #>__g_buf
    STA __zpR+1
    LDA __zpR
    STA __fn_memset_v_dst
    LDA __zpR+1
    STA __fn_memset_v_dst+1
    LDA #<65
    STA __zpR
    LDA #>65
    STA __zpR+1
    LDA __zpR
    STA __fn_memset_v_val
    LDA __zpR+1
    STA __fn_memset_v_val+1
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    LDA __zpR
    STA __fn_memset_v_n
    LDA __zpR+1
    STA __fn_memset_v_n+1
    JSR __fn_memset
    JSR __fn_memset_popframe
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_buf
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<__g_buf
    STA __zpR
    LDA #>__g_buf
    STA __zpR+1
    JSR __rt_puts
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_memcpy_pushframe
    LDA #<__g_buf2
    STA __zpR
    LDA #>__g_buf2
    STA __zpR+1
    LDA __zpR
    STA __fn_memcpy_v_dst
    LDA __zpR+1
    STA __fn_memcpy_v_dst+1
    LDA #<__g_buf
    STA __zpR
    LDA #>__g_buf
    STA __zpR+1
    LDA __zpR
    STA __fn_memcpy_v_src
    LDA __zpR+1
    STA __fn_memcpy_v_src+1
    LDA #<6
    STA __zpR
    LDA #>6
    STA __zpR+1
    LDA __zpR
    STA __fn_memcpy_v_n
    LDA __zpR+1
    STA __fn_memcpy_v_n+1
    JSR __fn_memcpy
    JSR __fn_memcpy_popframe
    LDA #<__g_buf2
    STA __zpR
    LDA #>__g_buf2
    STA __zpR+1
    JSR __rt_puts
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_hex_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_n
    LDA __zpR+1
    STA __fn_print_hex_v_n+1
    JSR __fn_print_hex
    JSR __fn_print_hex_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_hex_pushframe
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_n
    LDA __zpR+1
    STA __fn_print_hex_v_n+1
    JSR __fn_print_hex
    JSR __fn_print_hex_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_hex_pushframe
    LDA #<4096
    STA __zpR
    LDA #>4096
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_n
    LDA __zpR+1
    STA __fn_print_hex_v_n+1
    JSR __fn_print_hex
    JSR __fn_print_hex_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_hex_pushframe
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    LDA __zpR
    STA __fn_print_hex_v_n
    LDA __zpR+1
    STA __fn_print_hex_v_n+1
    JSR __fn_print_hex
    JSR __fn_print_hex_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_hex_pushframe
    LDA #<4096
    STA __zpR
    LDA #>4096
    STA __zpR+1
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    LDA __zpR
    STA __fn_print_hex_v_n
    LDA __zpR+1
    STA __fn_print_hex_v_n+1
    JSR __fn_print_hex
    JSR __fn_print_hex_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_count_matching_pushframe
    LDA #<__str_17
    STA __zpR
    LDA #>__str_17
    STA __zpR+1
    LDA __zpR
    STA __fn_count_matching_v_a
    LDA __zpR+1
    STA __fn_count_matching_v_a+1
    LDA #<__str_18
    STA __zpR
    LDA #>__str_18
    STA __zpR+1
    LDA __zpR
    STA __fn_count_matching_v_b
    LDA __zpR+1
    STA __fn_count_matching_v_b+1
    JSR __fn_count_matching
    JSR __fn_count_matching_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<__str_19
    STA __zpR
    LDA #>__str_19
    STA __zpR+1
    JSR __rt_puts
    RTS
 
; ---- string literals (raw bytes; __rt_puts converts at print time) ----
__str_0:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,67,65,76,76,32,83,84,65,67,75,32
    .byte 79,86,69,82,70,76,79,87,13,40,82,69,67,85,82,83,73,79,78,32,84,79,79,32,68,69,69,80,44,32,79,82
    .byte 32,77,73,83,83,73,78,71,32,66,65,83,69,32,67,65,83,69,41,13,0
__str_1:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,69,88,80,82,69,83,83,73,79,78,32
    .byte 83,84,65,67,75,32,79,86,69,82,70,76,79,87,13,40,69,88,80,82,69,83,83,73,79,78,83,32,78,69,83,84
    .byte 69,68,32,84,79,79,32,68,69,69,80,76,89,32,65,67,82,79,83,83,32,82,69,67,85,82,83,73,79,78,41,13
    .byte 0
__str_2:
    .byte 104,101,108,108,111,0
__str_3:
    .byte 0
__str_4:
    .byte 104,101,108,108,111,44,32,0
__str_5:
    .byte 119,111,114,108,100,33,0
__str_6:
    .byte 99,104,97,105,110,101,100,0
__str_7:
    .byte 97,98,99,0
__str_8:
    .byte 97,98,99,0
__str_9:
    .byte 97,98,99,0
__str_10:
    .byte 97,98,100,0
__str_11:
    .byte 97,98,100,0
__str_12:
    .byte 97,98,99,0
__str_13:
    .byte 97,98,0
__str_14:
    .byte 97,98,99,0
__str_15:
    .byte 104,101,108,108,111,44,32,119,111,114,108,100,33,0
__str_16:
    .byte 104,101,108,108,111,0
__str_17:
    .byte 97,98,99,100,101,102,0
__str_18:
    .byte 97,98,122,100,120,102,0
__str_19:
    .byte 68,79,78,69,46,0
 
; ---- operand stack (128 16-bit slots, indexed by __rt_spidx) -------
__rt_stack:
    .fill 256, 0
; ---- call stack (4096 bytes; see codegen_stmt.c's emit_function() ---
; ---- and codegen_runtime.c's cstack-check comment for what this is)--
__rt_cstack:
    .fill 4096, 0
