; Generated by cc64 from tests/recursion.c
; Assemble with: c64asm tests/recursion.asm -o program.prg
 
; ---- zero page pseudo-registers ---------------------------------
; Only $02/$03 and $FB-$FE are used here. Per the KERNAL's own
; memory map, those are the ONLY zero-page bytes confirmed genuinely
; free: $F3/$F4 is the current-line-in-color-RAM pointer (touched by
; CHROUT itself when it colors a printed character) and $F5/$F6 is the
; keyboard-matrix-to-PETSCII conversion table pointer (touched by the
; keyboard scan on every background IRQ, ~60x/sec) - both looked like
; safe 'adjacent' bytes but are not; this bit us for real once already.
__zpAP = $02      ; effective-address pointer (2 bytes) - needs zero
                  ; page because it's used with (zp),Y indirection
__zpR  = $FB      ; primary register / return value (2 bytes)
__zpR2 = $FD      ; secondary operand register (2 bytes)
__CHROUT = $FFD2
 
.basic
    LDA #14           ; switch to the lower/upper character set - required
    JSR __CHROUT      ; for the PETSCII case mapping below to render as letters
                      ; (the default charset only has graphics past $C0)
    LDA #0
    STA __rt_spidx
    LDA #<__rt_cstack ; call-stack pointer starts at the base of its buffer -
    STA __rt_csp      ; see codegen_stmt.c's emit_function() for how each
    LDA #>__rt_cstack ; function's push/popframe routines use it to support
    STA __rt_csp+1    ; recursion despite locals/params living at fixed addresses
    JSR __fn_main
    RTS
 
; ---- runtime scratch storage (plain RAM, NOT zero page - only __zpAP
; needs (zp),Y indirection; these are always accessed directly) -------
__rt_spidx:
    .byte 0
__rt_csp:
    .fill 2, 0
__zpT1:
    .fill 2, 0
__zpT0:
    .fill 2, 0
 
; ---- runtime library -------------------------------------------
__rt_push:
    LDX __rt_spidx
    LDA __zpR
    STA __rt_stack,X
    LDA __zpR+1
    STA __rt_stack+1,X
    INX
    INX
    STX __rt_spidx
    BNE __rt_push_ok
    LDA #<__str_1
    STA __zpR
    LDA #>__str_1
    STA __zpR+1
    JSR __rt_puts
__rt_push_halt:
    JMP __rt_push_halt
__rt_push_ok:
    RTS
 
__rt_pop2:
    LDX __rt_spidx
    DEX
    DEX
    LDA __rt_stack,X
    STA __zpR2
    LDA __rt_stack+1,X
    STA __zpR2+1
    STX __rt_spidx
    RTS
 
__rt_cstack_check:
    TSX
    CPX #$20
    BCC __rt_csc_overflow
    LDA __rt_csp+1
    CMP #>(__rt_cstack+4096)
    BCC __rt_csc_ok
    BNE __rt_csc_overflow
    LDA __rt_csp
    CMP #<(__rt_cstack+4096)
    BCC __rt_csc_ok
    BEQ __rt_csc_ok
__rt_csc_overflow:
    LDA #<__str_0
    STA __zpR
    LDA #>__str_0
    STA __zpR+1
    JSR __rt_puts
__rt_csc_halt:
    JMP __rt_csc_halt
__rt_csc_ok:
    RTS
 
__rt_mul16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_mul16_loop:
    LSR __zpR+1
    ROR __zpR
    BCC __rt_mul16_noadd
    CLC
    LDA __zpT0
    ADC __zpR2
    STA __zpT0
    LDA __zpT0+1
    ADC __zpR2+1
    STA __zpT0+1
__rt_mul16_noadd:
    ASL __zpR2
    ROL __zpR2+1
    DEX
    BNE __rt_mul16_loop
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    RTS
 
__rt_udiv16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_udiv16_loop:
    ASL __zpR2
    ROL __zpR2+1
    ROL __zpT0
    ROL __zpT0+1
    LDA __zpT0
    SEC
    SBC __zpR
    TAY
    LDA __zpT0+1
    SBC __zpR+1
    BCC __rt_udiv16_skip
    STA __zpT0+1
    STY __zpT0
    INC __zpR2
__rt_udiv16_skip:
    DEX
    BNE __rt_udiv16_loop
    RTS
 
__rt_neg_r2:
    SEC
    LDA #0
    SBC __zpR2
    TAX
    LDA #0
    SBC __zpR2+1
    STA __zpR2+1
    STX __zpR2
    RTS
 
__rt_neg_r:
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    RTS
 
__rt_neg_t0:
    SEC
    LDA #0
    SBC __zpT0
    TAX
    LDA #0
    SBC __zpT0+1
    STA __zpT0+1
    STX __zpT0
    RTS
 
__rt_sdivmod16:
    LDA #0
    STA __zpT1
    STA __zpT1+1
    LDA __zpR2+1
    BPL __rt_sdm_d1
    JSR __rt_neg_r2
    INC __zpT1
__rt_sdm_d1:
    LDA __zpR+1
    BPL __rt_sdm_d2
    JSR __rt_neg_r
    INC __zpT1+1
__rt_sdm_d2:
    JSR __rt_udiv16
    LDA __zpT1
    EOR __zpT1+1
    AND #1
    BEQ __rt_sdm_qdone
    JSR __rt_neg_r2
__rt_sdm_qdone:
    LDA __zpT1
    BEQ __rt_sdm_rdone
    JSR __rt_neg_t0
__rt_sdm_rdone:
    RTS
 
__rt_eq16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_eq16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_eq16_ne
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_eq16_ne:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_ne16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_ne16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_ne16_ne
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ne16_ne:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_sub_r2r:
    SEC
    LDA __zpR2
    SBC __zpR
    LDA __zpR2+1
    SBC __zpR+1
    BVC __rt_sub_r2r_ok
    EOR #$80
__rt_sub_r2r_ok:
    RTS
 
__rt_sub_rr2:
    SEC
    LDA __zpR
    SBC __zpR2
    LDA __zpR+1
    SBC __zpR2+1
    BVC __rt_sub_rr2_ok
    EOR #$80
__rt_sub_rr2_ok:
    RTS
 
__rt_lt16:
    JSR __rt_sub_r2r
    BMI __rt_lt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_lt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ge16:
    JSR __rt_sub_r2r
    BPL __rt_ge16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_gt16:
    JSR __rt_sub_rr2
    BMI __rt_gt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_gt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_le16:
    JSR __rt_sub_rr2
    BPL __rt_le16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_le16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_shl16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shl16_loop:
    CPX #0
    BEQ __rt_shl16_done
    ASL __zpR
    ROL __zpR+1
    DEX
    JMP __rt_shl16_loop
__rt_shl16_done:
    RTS
 
__rt_shr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shr16_loop:
    CPX #0
    BEQ __rt_shr16_done
    LDA __zpR+1
    CMP #$80
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_shr16_loop
__rt_shr16_done:
    RTS
 
__rt_topetscii:
    LDA __zpR
    CMP #$61
    BCC __rt_tp_notlower
    CMP #$7B
    BCS __rt_tp_notlower
    SEC
    SBC #$20
    STA __zpR
    JMP __rt_tp_done
__rt_tp_notlower:
    CMP #$41
    BCC __rt_tp_done
    CMP #$5B
    BCS __rt_tp_done
    CLC
    ADC #$80
    STA __zpR
__rt_tp_done:
    RTS
 
__rt_ult16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_ult16_t
    BNE __rt_ult16_f
    LDA __zpR2
    CMP __zpR
    BCC __rt_ult16_t
__rt_ult16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ult16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ugt16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ugt16_t
    BNE __rt_ugt16_f
    LDA __zpR
    CMP __zpR2
    BCC __rt_ugt16_t
__rt_ugt16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ugt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ule16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ule16_f
    BNE __rt_ule16_t
    LDA __zpR
    CMP __zpR2
    BCC __rt_ule16_f
__rt_ule16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_ule16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_uge16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_uge16_f
    BNE __rt_uge16_t
    LDA __zpR2
    CMP __zpR
    BCC __rt_uge16_f
__rt_uge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_uge16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_puts:
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
__rt_puts_loop:
    LDY #0
    LDA (__zpAP),Y
    BEQ __rt_puts_done
    STA __zpR
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    CLC
    LDA __zpAP
    ADC #1
    STA __zpAP
    LDA __zpAP+1
    ADC #0
    STA __zpAP+1
    JMP __rt_puts_loop
__rt_puts_done:
    RTS
 
; ---- global variables --------------------------------------------
__g_g_calls:
    .word 0
__g_garr:
    .fill 8, 0
__g_gother:
    .fill 8, 0
 
; ---- function print_uint ---------------------------------------------
__fn_print_uint_frame:
__fn_print_uint_v_n:
    .fill 2, 0
__fn_print_uint_v_buf:
    .fill 6, 0
__fn_print_uint_v_i:
    .fill 2, 0
__fn_print_uint_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_uint_pushfr_loop:
    LDA __fn_print_uint_frame,Y
    STA (__zpAP),Y
    INY
    CPY #10
    BNE __fn_print_uint_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #10
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_uint_popframe:
    SEC
    LDA __rt_csp
    SBC #10
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_uint_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_uint_frame,Y
    INY
    CPY #10
    BNE __fn_print_uint_popfr_loop
    RTS
 
__fn_print_uint:
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L2
    JMP __L0
__L2:
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
    JMP __L1
__L0:
__L1:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
__L3:
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L5
    JMP __L4
__L5:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_uint_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_uint_v_buf
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_print_uint_v_n
    STA __zpR
    LDA __fn_print_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_n
    LDA __zpR+1
    STA __fn_print_uint_v_n+1
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
    JMP __L3
__L4:
__L6:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L8
    JMP __L7
__L8:
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_uint_v_i
    LDA __zpR+1
    STA __fn_print_uint_v_i+1
    LDA __fn_print_uint_v_i
    STA __zpR
    LDA __fn_print_uint_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_uint_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_uint_v_buf
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L6
__L7:
    RTS
 
; ---- function print_int ---------------------------------------------
__fn_print_int_frame:
__fn_print_int_v_n:
    .fill 2, 0
__fn_print_int_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_int_pushfr_loop:
    LDA __fn_print_int_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_print_int_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_int_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_int_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_int_frame,Y
    INY
    CPY #2
    BNE __fn_print_int_popfr_loop
    RTS
 
__fn_print_int:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L11
    JMP __L9
__L11:
    LDA #<45
    STA __zpR
    LDA #>45
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JSR __fn_print_uint_pushframe
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    LDA __zpR
    STA __fn_print_uint_v_n
    LDA __zpR+1
    STA __fn_print_uint_v_n+1
    JSR __fn_print_uint
    JSR __fn_print_uint_popframe
    JMP __L10
__L9:
    JSR __fn_print_uint_pushframe
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_uint_v_n
    LDA __zpR+1
    STA __fn_print_uint_v_n+1
    JSR __fn_print_uint
    JSR __fn_print_uint_popframe
__L10:
    RTS
 
; ---- function nl ---------------------------------------------
__fn_nl_frame:
__fn_nl_pushframe:
    RTS
 
__fn_nl_popframe:
    RTS
 
__fn_nl:
    LDA #<13
    STA __zpR
    LDA #>13
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
 
; ---- function fact ---------------------------------------------
__fn_fact_frame:
__fn_fact_v_n:
    .fill 2, 0
__fn_fact_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_fact_pushfr_loop:
    LDA __fn_fact_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_fact_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_fact_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_fact_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_fact_frame,Y
    INY
    CPY #2
    BNE __fn_fact_popfr_loop
    RTS
 
__fn_fact:
    LDA __fn_fact_v_n
    STA __zpR
    LDA __fn_fact_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_le16
    LDA __zpR
    ORA __zpR+1
    BNE __L14
    JMP __L12
__L14:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    RTS
    JMP __L13
__L12:
__L13:
    LDA __fn_fact_v_n
    STA __zpR
    LDA __fn_fact_v_n+1
    STA __zpR+1
    JSR __rt_push
    JSR __fn_fact_pushframe
    LDA __fn_fact_v_n
    STA __zpR
    LDA __fn_fact_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_fact_v_n
    LDA __zpR+1
    STA __fn_fact_v_n+1
    JSR __fn_fact
    JSR __fn_fact_popframe
    JSR __rt_pop2
    JSR __rt_mul16
    RTS
    RTS
 
; ---- function fib ---------------------------------------------
__fn_fib_frame:
__fn_fib_v_n:
    .fill 2, 0
__fn_fib_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_fib_pushfr_loop:
    LDA __fn_fib_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_fib_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_fib_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_fib_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_fib_frame,Y
    INY
    CPY #2
    BNE __fn_fib_popfr_loop
    RTS
 
__fn_fib:
    LDA __fn_fib_v_n
    STA __zpR
    LDA __fn_fib_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L17
    JMP __L15
__L17:
    LDA __fn_fib_v_n
    STA __zpR
    LDA __fn_fib_v_n+1
    STA __zpR+1
    RTS
    JMP __L16
__L15:
__L16:
    JSR __fn_fib_pushframe
    LDA __fn_fib_v_n
    STA __zpR
    LDA __fn_fib_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_fib_v_n
    LDA __zpR+1
    STA __fn_fib_v_n+1
    JSR __fn_fib
    JSR __fn_fib_popframe
    JSR __rt_push
    JSR __fn_fib_pushframe
    LDA __fn_fib_v_n
    STA __zpR
    LDA __fn_fib_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_fib_v_n
    LDA __zpR+1
    STA __fn_fib_v_n+1
    JSR __fn_fib
    JSR __fn_fib_popframe
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function is_odd ---------------------------------------------
__fn_is_odd_frame:
__fn_is_odd_v_n:
    .fill 2, 0
__fn_is_odd_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_is_odd_pushfr_loop:
    LDA __fn_is_odd_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_is_odd_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_is_odd_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_is_odd_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_is_odd_frame,Y
    INY
    CPY #2
    BNE __fn_is_odd_popfr_loop
    RTS
 
__fn_is_odd:
    LDA __fn_is_odd_v_n
    STA __zpR
    LDA __fn_is_odd_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L20
    JMP __L18
__L20:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    RTS
    JMP __L19
__L18:
__L19:
    JSR __fn_is_even_pushframe
    LDA __fn_is_odd_v_n
    STA __zpR
    LDA __fn_is_odd_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_is_even_v_n
    LDA __zpR+1
    STA __fn_is_even_v_n+1
    JSR __fn_is_even
    JSR __fn_is_even_popframe
    RTS
    RTS
 
; ---- function is_even ---------------------------------------------
__fn_is_even_frame:
__fn_is_even_v_n:
    .fill 2, 0
__fn_is_even_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_is_even_pushfr_loop:
    LDA __fn_is_even_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_is_even_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_is_even_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_is_even_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_is_even_frame,Y
    INY
    CPY #2
    BNE __fn_is_even_popfr_loop
    RTS
 
__fn_is_even:
    LDA __fn_is_even_v_n
    STA __zpR
    LDA __fn_is_even_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L23
    JMP __L21
__L23:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    RTS
    JMP __L22
__L21:
__L22:
    JSR __fn_is_odd_pushframe
    LDA __fn_is_even_v_n
    STA __zpR
    LDA __fn_is_even_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_is_odd_v_n
    LDA __zpR+1
    STA __fn_is_odd_v_n+1
    JSR __fn_is_odd
    JSR __fn_is_odd_popframe
    RTS
    RTS
 
; ---- function rprint_uint ---------------------------------------------
__fn_rprint_uint_frame:
__fn_rprint_uint_v_n:
    .fill 2, 0
__fn_rprint_uint_v_digit:
    .fill 2, 0
__fn_rprint_uint_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_rprint_uint_pushfr_loop:
    LDA __fn_rprint_uint_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_rprint_uint_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_rprint_uint_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_rprint_uint_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_rprint_uint_frame,Y
    INY
    CPY #4
    BNE __fn_rprint_uint_popfr_loop
    RTS
 
__fn_rprint_uint:
    LDA __fn_rprint_uint_v_n
    STA __zpR
    LDA __fn_rprint_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    LDA __zpR
    STA __fn_rprint_uint_v_digit
    LDA __zpR+1
    STA __fn_rprint_uint_v_digit+1
    LDA __fn_rprint_uint_v_n
    STA __zpR
    LDA __fn_rprint_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ge16
    LDA __zpR
    ORA __zpR+1
    BNE __L26
    JMP __L24
__L26:
    JSR __fn_rprint_uint_pushframe
    LDA __fn_rprint_uint_v_n
    STA __zpR
    LDA __fn_rprint_uint_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_rprint_uint_v_n
    LDA __zpR+1
    STA __fn_rprint_uint_v_n+1
    JSR __fn_rprint_uint
    JSR __fn_rprint_uint_popframe
    JMP __L25
__L24:
__L25:
    LDA __fn_rprint_uint_v_digit
    STA __zpR
    LDA __fn_rprint_uint_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
 
; ---- function rstrlen ---------------------------------------------
__fn_rstrlen_frame:
__fn_rstrlen_v_s:
    .fill 2, 0
__fn_rstrlen_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_rstrlen_pushfr_loop:
    LDA __fn_rstrlen_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_rstrlen_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_rstrlen_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_rstrlen_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_rstrlen_frame,Y
    INY
    CPY #2
    BNE __fn_rstrlen_popfr_loop
    RTS
 
__fn_rstrlen:
    LDA __fn_rstrlen_v_s
    STA __zpR
    LDA __fn_rstrlen_v_s+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L29
    JMP __L27
__L29:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    RTS
    JMP __L28
__L27:
__L28:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    JSR __fn_rstrlen_pushframe
    LDA __fn_rstrlen_v_s
    STA __zpR
    LDA __fn_rstrlen_v_s+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_rstrlen_v_s
    LDA __zpR+1
    STA __fn_rstrlen_v_s+1
    JSR __fn_rstrlen
    JSR __fn_rstrlen_popframe
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function depth_count ---------------------------------------------
__fn_depth_count_frame:
__fn_depth_count_v_n:
    .fill 2, 0
__fn_depth_count_v_counter:
    .fill 2, 0
__fn_depth_count_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_depth_count_pushfr_loop:
    LDA __fn_depth_count_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_depth_count_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_depth_count_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_depth_count_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_depth_count_frame,Y
    INY
    CPY #4
    BNE __fn_depth_count_popfr_loop
    RTS
 
__fn_depth_count:
    LDA __fn_depth_count_v_counter
    STA __zpR
    LDA __fn_depth_count_v_counter+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_depth_count_v_counter
    STA __zpR
    LDA __fn_depth_count_v_counter+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
    LDA __fn_depth_count_v_n
    STA __zpR
    LDA __fn_depth_count_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_le16
    LDA __zpR
    ORA __zpR+1
    BNE __L32
    JMP __L30
__L32:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    RTS
    JMP __L31
__L30:
__L31:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    JSR __fn_depth_count_pushframe
    LDA __fn_depth_count_v_n
    STA __zpR
    LDA __fn_depth_count_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_depth_count_v_n
    LDA __zpR+1
    STA __fn_depth_count_v_n+1
    LDA __fn_depth_count_v_counter
    STA __zpR
    LDA __fn_depth_count_v_counter+1
    STA __zpR+1
    LDA __zpR
    STA __fn_depth_count_v_counter
    LDA __zpR+1
    STA __fn_depth_count_v_counter+1
    JSR __fn_depth_count
    JSR __fn_depth_count_popframe
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function arr_check ---------------------------------------------
__fn_arr_check_frame:
__fn_arr_check_v_n:
    .fill 2, 0
__fn_arr_check_v_a:
    .fill 8, 0
__fn_arr_check_v_i:
    .fill 2, 0
__fn_arr_check_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_arr_check_pushfr_loop:
    LDA __fn_arr_check_frame,Y
    STA (__zpAP),Y
    INY
    CPY #12
    BNE __fn_arr_check_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #12
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_arr_check_popframe:
    SEC
    LDA __rt_csp
    SBC #12
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_arr_check_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_arr_check_frame,Y
    INY
    CPY #12
    BNE __fn_arr_check_popfr_loop
    RTS
 
__fn_arr_check:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_arr_check_v_i
    LDA __zpR+1
    STA __fn_arr_check_v_i+1
__L33:
    LDA __fn_arr_check_v_i
    STA __zpR
    LDA __fn_arr_check_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L36
    JMP __L34
__L36:
    LDA __fn_arr_check_v_i
    STA __zpR
    LDA __fn_arr_check_v_i+1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_arr_check_v_a
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_arr_check_v_a
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_arr_check_v_n
    STA __zpR
    LDA __fn_arr_check_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_push
    LDA __fn_arr_check_v_i
    STA __zpR
    LDA __fn_arr_check_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
__L35:
    LDA __fn_arr_check_v_i
    STA __zpR
    LDA __fn_arr_check_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_arr_check_v_i
    LDA __zpR+1
    STA __fn_arr_check_v_i+1
    JMP __L33
__L34:
    LDA __fn_arr_check_v_n
    STA __zpR
    LDA __fn_arr_check_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L39
    JMP __L37
__L39:
    JSR __fn_arr_check_pushframe
    LDA __fn_arr_check_v_n
    STA __zpR
    LDA __fn_arr_check_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_arr_check_v_n
    LDA __zpR+1
    STA __fn_arr_check_v_n+1
    JSR __fn_arr_check
    JSR __fn_arr_check_popframe
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L42
    JMP __L40
__L42:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    RTS
    JMP __L41
__L40:
__L41:
    JMP __L38
__L37:
__L38:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_arr_check_v_i
    LDA __zpR+1
    STA __fn_arr_check_v_i+1
__L43:
    LDA __fn_arr_check_v_i
    STA __zpR
    LDA __fn_arr_check_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L46
    JMP __L44
__L46:
    LDA __fn_arr_check_v_i
    STA __zpR
    LDA __fn_arr_check_v_i+1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_arr_check_v_a
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_arr_check_v_a
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_push
    LDA __fn_arr_check_v_n
    STA __zpR
    LDA __fn_arr_check_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_push
    LDA __fn_arr_check_v_i
    STA __zpR
    LDA __fn_arr_check_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ne16
    LDA __zpR
    ORA __zpR+1
    BNE __L49
    JMP __L47
__L49:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    RTS
    JMP __L48
__L47:
__L48:
__L45:
    LDA __fn_arr_check_v_i
    STA __zpR
    LDA __fn_arr_check_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_arr_check_v_i
    LDA __zpR+1
    STA __fn_arr_check_v_i+1
    JMP __L43
__L44:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    RTS
    RTS
 
; ---- function rsum ---------------------------------------------
__fn_rsum_frame:
__fn_rsum_v_n:
    .fill 2, 0
__fn_rsum_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_rsum_pushfr_loop:
    LDA __fn_rsum_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_rsum_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_rsum_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_rsum_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_rsum_frame,Y
    INY
    CPY #2
    BNE __fn_rsum_popfr_loop
    RTS
 
__fn_rsum:
    LDA __fn_rsum_v_n
    STA __zpR
    LDA __fn_rsum_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L52
    JMP __L50
__L52:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    RTS
    JMP __L51
__L50:
__L51:
    LDA __fn_rsum_v_n
    STA __zpR
    LDA __fn_rsum_v_n+1
    STA __zpR+1
    JSR __rt_push
    JSR __fn_rsum_pushframe
    LDA __fn_rsum_v_n
    STA __zpR
    LDA __fn_rsum_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_rsum_v_n
    LDA __zpR+1
    STA __fn_rsum_v_n+1
    JSR __fn_rsum
    JSR __fn_rsum_popframe
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function identity ---------------------------------------------
__fn_identity_frame:
__fn_identity_v_x:
    .fill 2, 0
__fn_identity_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_identity_pushfr_loop:
    LDA __fn_identity_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_identity_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_identity_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_identity_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_identity_frame,Y
    INY
    CPY #2
    BNE __fn_identity_popfr_loop
    RTS
 
__fn_identity:
    LDA __fn_identity_v_x
    STA __zpR
    LDA __fn_identity_v_x+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function main ---------------------------------------------
__fn_main_frame:
__fn_main_v_c:
    .fill 2, 0
__fn_main_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_main_pushfr_loop:
    LDA __fn_main_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_main_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_main_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_main_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_main_frame,Y
    INY
    CPY #2
    BNE __fn_main_popfr_loop
    RTS
 
__fn_main:
    JSR __fn_print_int_pushframe
    JSR __fn_fact_pushframe
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    LDA __zpR
    STA __fn_fact_v_n
    LDA __zpR+1
    STA __fn_fact_v_n+1
    JSR __fn_fact
    JSR __fn_fact_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_fact_pushframe
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    LDA __zpR
    STA __fn_fact_v_n
    LDA __zpR+1
    STA __fn_fact_v_n+1
    JSR __fn_fact
    JSR __fn_fact_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_fib_pushframe
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    LDA __zpR
    STA __fn_fib_v_n
    LDA __zpR+1
    STA __fn_fib_v_n+1
    JSR __fn_fib
    JSR __fn_fib_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_fib_pushframe
    LDA #<15
    STA __zpR
    LDA #>15
    STA __zpR+1
    LDA __zpR
    STA __fn_fib_v_n
    LDA __zpR+1
    STA __fn_fib_v_n+1
    JSR __fn_fib
    JSR __fn_fib_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_is_even_pushframe
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    LDA __zpR
    STA __fn_is_even_v_n
    LDA __zpR+1
    STA __fn_is_even_v_n+1
    JSR __fn_is_even
    JSR __fn_is_even_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_is_even_pushframe
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    LDA __zpR
    STA __fn_is_even_v_n
    LDA __zpR+1
    STA __fn_is_even_v_n+1
    JSR __fn_is_even
    JSR __fn_is_even_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_is_odd_pushframe
    LDA #<9
    STA __zpR
    LDA #>9
    STA __zpR+1
    LDA __zpR
    STA __fn_is_odd_v_n
    LDA __zpR+1
    STA __fn_is_odd_v_n+1
    JSR __fn_is_odd
    JSR __fn_is_odd_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_rprint_uint_pushframe
    LDA #<9
    STA __zpR
    LDA #>9
    STA __zpR+1
    LDA __zpR
    STA __fn_rprint_uint_v_n
    LDA __zpR+1
    STA __fn_rprint_uint_v_n+1
    JSR __fn_rprint_uint
    JSR __fn_rprint_uint_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_rprint_uint_pushframe
    LDA #<408
    STA __zpR
    LDA #>408
    STA __zpR+1
    LDA __zpR
    STA __fn_rprint_uint_v_n
    LDA __zpR+1
    STA __fn_rprint_uint_v_n+1
    JSR __fn_rprint_uint
    JSR __fn_rprint_uint_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_rprint_uint_pushframe
    LDA #<31337
    STA __zpR
    LDA #>31337
    STA __zpR+1
    LDA __zpR
    STA __fn_rprint_uint_v_n
    LDA __zpR+1
    STA __fn_rprint_uint_v_n+1
    JSR __fn_rprint_uint
    JSR __fn_rprint_uint_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_rstrlen_pushframe
    LDA #<__str_2
    STA __zpR
    LDA #>__str_2
    STA __zpR+1
    LDA __zpR
    STA __fn_rstrlen_v_s
    LDA __zpR+1
    STA __fn_rstrlen_v_s+1
    JSR __fn_rstrlen
    JSR __fn_rstrlen_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_rstrlen_pushframe
    LDA #<__str_3
    STA __zpR
    LDA #>__str_3
    STA __zpR+1
    LDA __zpR
    STA __fn_rstrlen_v_s
    LDA __zpR+1
    STA __fn_rstrlen_v_s+1
    JSR __fn_rstrlen
    JSR __fn_rstrlen_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_c
    LDA __zpR+1
    STA __fn_main_v_c+1
    JSR __fn_print_int_pushframe
    JSR __fn_depth_count_pushframe
    LDA #<6
    STA __zpR
    LDA #>6
    STA __zpR+1
    LDA __zpR
    STA __fn_depth_count_v_n
    LDA __zpR+1
    STA __fn_depth_count_v_n+1
    LDA #<__fn_main_v_c
    STA __zpR
    LDA #>__fn_main_v_c
    STA __zpR+1
    LDA __zpR
    STA __fn_depth_count_v_counter
    LDA __zpR+1
    STA __fn_depth_count_v_counter+1
    JSR __fn_depth_count
    JSR __fn_depth_count_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_c
    STA __zpR
    LDA __fn_main_v_c+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_arr_check_pushframe
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    LDA __zpR
    STA __fn_arr_check_v_n
    LDA __zpR+1
    STA __fn_arr_check_v_n+1
    JSR __fn_arr_check
    JSR __fn_arr_check_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_rsum_pushframe
    LDA #<80
    STA __zpR
    LDA #>80
    STA __zpR+1
    LDA __zpR
    STA __fn_rsum_v_n
    LDA __zpR+1
    STA __fn_rsum_v_n+1
    JSR __fn_rsum
    JSR __fn_rsum_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_gother
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_gother
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    JSR __fn_identity_pushframe
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    LDA __zpR
    STA __fn_identity_v_x
    LDA __zpR+1
    STA __fn_identity_v_x+1
    JSR __fn_identity
    JSR __fn_identity_popframe
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    INY
    LDA __zpR+1
    STA (__zpAP),Y
    JSR __fn_print_int_pushframe
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_garr
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_garr
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    JSR __fn_print_int_pushframe
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    ASL __zpR
    ROL __zpR+1
    CLC
    LDA __zpR
    ADC #<__g_gother
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_gother
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    INY
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_nl_pushframe
    JSR __fn_nl
    JSR __fn_nl_popframe
    LDA #<__str_4
    STA __zpR
    LDA #>__str_4
    STA __zpR+1
    JSR __rt_puts
    RTS
 
; ---- string literals (raw bytes; __rt_puts converts at print time) ----
__str_0:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,67,65,76,76,32,83,84,65,67,75,32
    .byte 79,86,69,82,70,76,79,87,13,40,82,69,67,85,82,83,73,79,78,32,84,79,79,32,68,69,69,80,44,32,79,82
    .byte 32,77,73,83,83,73,78,71,32,66,65,83,69,32,67,65,83,69,41,13,0
__str_1:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,69,88,80,82,69,83,83,73,79,78,32
    .byte 83,84,65,67,75,32,79,86,69,82,70,76,79,87,13,40,69,88,80,82,69,83,83,73,79,78,83,32,78,69,83,84
    .byte 69,68,32,84,79,79,32,68,69,69,80,76,89,32,65,67,82,79,83,83,32,82,69,67,85,82,83,73,79,78,41,13
    .byte 0
__str_2:
    .byte 104,101,108,108,111,0
__str_3:
    .byte 0
__str_4:
    .byte 68,79,78,69,46,0
 
; ---- operand stack (128 16-bit slots, indexed by __rt_spidx) -------
__rt_stack:
    .fill 256, 0
; ---- call stack (4096 bytes; see codegen_stmt.c's emit_function() ---
; ---- and codegen_runtime.c's cstack-check comment for what this is)--
__rt_cstack:
    .fill 4096, 0
