; Generated by cc64 from ./tests/structs.c
; Assemble with: c64asm ./tests/structs.asm -o program.prg
 
; ---- zero page pseudo-registers ---------------------------------
; Only $02/$03 and $FB-$FE are used here. Per the KERNAL's own
; memory map, those are the ONLY zero-page bytes confirmed genuinely
; free: $F3/$F4 is the current-line-in-color-RAM pointer (touched by
; CHROUT itself when it colors a printed character) and $F5/$F6 is the
; keyboard-matrix-to-PETSCII conversion table pointer (touched by the
; keyboard scan on every background IRQ, ~60x/sec) - both looked like
; safe 'adjacent' bytes but are not; this bit us for real once already.
__zpAP = $02      ; effective-address pointer (2 bytes) - needs zero
                  ; page because it's used with (zp),Y indirection
__zpR  = $FB      ; primary register / return value (2 bytes)
__zpR2 = $FD      ; secondary operand register (2 bytes)
__CHROUT = $FFD2
 
.basic
    LDA #14           ; switch to the lower/upper character set - required
    JSR __CHROUT      ; for the PETSCII case mapping below to render as letters
                      ; (the default charset only has graphics past $C0)
    LDA #0
    STA __rt_spidx
    LDA #<__rt_cstack ; call-stack pointer starts at the base of its buffer -
    STA __rt_csp      ; see codegen_stmt.c's emit_function() for how each
    LDA #>__rt_cstack ; function's push/popframe routines use it to support
    STA __rt_csp+1    ; recursion despite locals/params living at fixed addresses
    JSR __fn_main
    RTS
 
; ---- runtime scratch storage (plain RAM, NOT zero page - only __zpAP
; needs (zp),Y indirection; these are always accessed directly) -------
__rt_spidx:
    .byte 0
__rt_csp:
    .fill 2, 0
__zpT1:
    .fill 2, 0
__zpT0:
    .fill 2, 0
 
; ---- runtime library -------------------------------------------
__rt_push:
    LDX __rt_spidx
    LDA __zpR
    STA __rt_stack,X
    LDA __zpR+1
    STA __rt_stack+1,X
    INX
    INX
    STX __rt_spidx
    BNE __rt_push_ok
    LDA #<__str_1
    STA __zpR
    LDA #>__str_1
    STA __zpR+1
    JSR __rt_puts
__rt_push_halt:
    JMP __rt_push_halt
__rt_push_ok:
    RTS
 
__rt_pop2:
    LDX __rt_spidx
    DEX
    DEX
    LDA __rt_stack,X
    STA __zpR2
    LDA __rt_stack+1,X
    STA __zpR2+1
    STX __rt_spidx
    RTS
 
__rt_cstack_check:
    TSX
    CPX #$20
    BCC __rt_csc_overflow
    LDA __rt_csp+1
    CMP #>(__rt_cstack+4096)
    BCC __rt_csc_ok
    BNE __rt_csc_overflow
    LDA __rt_csp
    CMP #<(__rt_cstack+4096)
    BCC __rt_csc_ok
    BEQ __rt_csc_ok
__rt_csc_overflow:
    LDA #<__str_0
    STA __zpR
    LDA #>__str_0
    STA __zpR+1
    JSR __rt_puts
__rt_csc_halt:
    JMP __rt_csc_halt
__rt_csc_ok:
    RTS
 
__rt_mul16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_mul16_loop:
    LSR __zpR+1
    ROR __zpR
    BCC __rt_mul16_noadd
    CLC
    LDA __zpT0
    ADC __zpR2
    STA __zpT0
    LDA __zpT0+1
    ADC __zpR2+1
    STA __zpT0+1
__rt_mul16_noadd:
    ASL __zpR2
    ROL __zpR2+1
    DEX
    BNE __rt_mul16_loop
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    RTS
 
__rt_udiv16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_udiv16_loop:
    ASL __zpR2
    ROL __zpR2+1
    ROL __zpT0
    ROL __zpT0+1
    LDA __zpT0
    SEC
    SBC __zpR
    TAY
    LDA __zpT0+1
    SBC __zpR+1
    BCC __rt_udiv16_skip
    STA __zpT0+1
    STY __zpT0
    INC __zpR2
__rt_udiv16_skip:
    DEX
    BNE __rt_udiv16_loop
    RTS
 
__rt_neg_r2:
    SEC
    LDA #0
    SBC __zpR2
    TAX
    LDA #0
    SBC __zpR2+1
    STA __zpR2+1
    STX __zpR2
    RTS
 
__rt_neg_r:
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    RTS
 
__rt_neg_t0:
    SEC
    LDA #0
    SBC __zpT0
    TAX
    LDA #0
    SBC __zpT0+1
    STA __zpT0+1
    STX __zpT0
    RTS
 
__rt_sdivmod16:
    LDA #0
    STA __zpT1
    STA __zpT1+1
    LDA __zpR2+1
    BPL __rt_sdm_d1
    JSR __rt_neg_r2
    INC __zpT1
__rt_sdm_d1:
    LDA __zpR+1
    BPL __rt_sdm_d2
    JSR __rt_neg_r
    INC __zpT1+1
__rt_sdm_d2:
    JSR __rt_udiv16
    LDA __zpT1
    EOR __zpT1+1
    AND #1
    BEQ __rt_sdm_qdone
    JSR __rt_neg_r2
__rt_sdm_qdone:
    LDA __zpT1
    BEQ __rt_sdm_rdone
    JSR __rt_neg_t0
__rt_sdm_rdone:
    RTS
 
__rt_eq16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_eq16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_eq16_ne
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_eq16_ne:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_ne16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_ne16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_ne16_ne
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ne16_ne:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_sub_r2r:
    SEC
    LDA __zpR2
    SBC __zpR
    LDA __zpR2+1
    SBC __zpR+1
    BVC __rt_sub_r2r_ok
    EOR #$80
__rt_sub_r2r_ok:
    RTS
 
__rt_sub_rr2:
    SEC
    LDA __zpR
    SBC __zpR2
    LDA __zpR+1
    SBC __zpR2+1
    BVC __rt_sub_rr2_ok
    EOR #$80
__rt_sub_rr2_ok:
    RTS
 
__rt_lt16:
    JSR __rt_sub_r2r
    BMI __rt_lt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_lt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ge16:
    JSR __rt_sub_r2r
    BPL __rt_ge16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_gt16:
    JSR __rt_sub_rr2
    BMI __rt_gt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_gt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_le16:
    JSR __rt_sub_rr2
    BPL __rt_le16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_le16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_shl16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shl16_loop:
    CPX #0
    BEQ __rt_shl16_done
    ASL __zpR
    ROL __zpR+1
    DEX
    JMP __rt_shl16_loop
__rt_shl16_done:
    RTS
 
__rt_shr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shr16_loop:
    CPX #0
    BEQ __rt_shr16_done
    LDA __zpR+1
    CMP #$80
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_shr16_loop
__rt_shr16_done:
    RTS
 
__rt_topetscii:
    LDA __zpR
    CMP #$61
    BCC __rt_tp_notlower
    CMP #$7B
    BCS __rt_tp_notlower
    SEC
    SBC #$20
    STA __zpR
    JMP __rt_tp_done
__rt_tp_notlower:
    CMP #$41
    BCC __rt_tp_done
    CMP #$5B
    BCS __rt_tp_done
    CLC
    ADC #$80
    STA __zpR
__rt_tp_done:
    RTS
 
__rt_ult16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_ult16_t
    BNE __rt_ult16_f
    LDA __zpR2
    CMP __zpR
    BCC __rt_ult16_t
__rt_ult16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ult16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ugt16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ugt16_t
    BNE __rt_ugt16_f
    LDA __zpR
    CMP __zpR2
    BCC __rt_ugt16_t
__rt_ugt16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ugt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ule16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ule16_f
    BNE __rt_ule16_t
    LDA __zpR
    CMP __zpR2
    BCC __rt_ule16_f
__rt_ule16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_ule16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_uge16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_uge16_f
    BNE __rt_uge16_t
    LDA __zpR2
    CMP __zpR
    BCC __rt_uge16_f
__rt_uge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_uge16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_puts:
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
__rt_puts_loop:
    LDY #0
    LDA (__zpAP),Y
    BEQ __rt_puts_done
    STA __zpR
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    CLC
    LDA __zpAP
    ADC #1
    STA __zpAP
    LDA __zpAP+1
    ADC #0
    STA __zpAP+1
    JMP __rt_puts_loop
__rt_puts_done:
    RTS
 
; ---- global variables --------------------------------------------
__g_g_origin:
    .fill 4, 0
__g_g_pts:
    .fill 16, 0
__g_g_head:
    .fill 2, 0
 
; ---- function print_int ---------------------------------------------
__fn_print_int_frame:
__fn_print_int_v_n:
    .fill 2, 0
__fn_print_int_v_buf:
    .fill 6, 0
__fn_print_int_v_i:
    .fill 2, 0
__fn_print_int_v_neg:
    .fill 2, 0
__fn_print_int_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_int_pushfr_loop:
    LDA __fn_print_int_frame,Y
    STA (__zpAP),Y
    INY
    CPY #12
    BNE __fn_print_int_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #12
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_int_popframe:
    SEC
    LDA __rt_csp
    SBC #12
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_int_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_int_frame,Y
    INY
    CPY #12
    BNE __fn_print_int_popfr_loop
    RTS
 
__fn_print_int:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_neg
    LDA __zpR+1
    STA __fn_print_int_v_neg+1
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L2
    JMP __L0
__L2:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_neg
    LDA __zpR+1
    STA __fn_print_int_v_neg+1
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JMP __L1
__L0:
__L1:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L5
    JMP __L3
__L5:
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
    JMP __L4
__L3:
__L4:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
__L6:
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L8
    JMP __L7
__L8:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_int_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_int_v_buf
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_print_int_v_n
    STA __zpR
    LDA __fn_print_int_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
    JMP __L6
__L7:
    LDA __fn_print_int_v_neg
    STA __zpR
    LDA __fn_print_int_v_neg+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L11
    JMP __L9
__L11:
    LDA #<45
    STA __zpR
    LDA #>45
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L10
__L9:
__L10:
__L12:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L14
    JMP __L13
__L14:
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_int_v_i
    LDA __zpR+1
    STA __fn_print_int_v_i+1
    LDA __fn_print_int_v_i
    STA __zpR
    LDA __fn_print_int_v_i+1
    STA __zpR+1
    CLC
    LDA __zpR
    ADC #<__fn_print_int_v_buf
    STA __zpAP
    LDA __zpR+1
    ADC #>__fn_print_int_v_buf
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L12
__L13:
    RTS
 
; ---- function print_hex ---------------------------------------------
__fn_print_hex_frame:
__fn_print_hex_v_n:
    .fill 2, 0
__fn_print_hex_v_i:
    .fill 2, 0
__fn_print_hex_v_shift:
    .fill 2, 0
__fn_print_hex_v_digit:
    .fill 2, 0
__fn_print_hex_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_hex_pushfr_loop:
    LDA __fn_print_hex_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_print_hex_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_print_hex_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_print_hex_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_print_hex_frame,Y
    INY
    CPY #8
    BNE __fn_print_hex_popfr_loop
    RTS
 
__fn_print_hex:
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_i
    LDA __zpR+1
    STA __fn_print_hex_v_i+1
__L15:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ge16
    LDA __zpR
    ORA __zpR+1
    BNE __L18
    JMP __L16
__L18:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    LDA __zpR
    STA __fn_print_hex_v_shift
    LDA __zpR+1
    STA __fn_print_hex_v_shift+1
    LDA __fn_print_hex_v_n
    STA __zpR
    LDA __fn_print_hex_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_print_hex_v_shift
    STA __zpR
    LDA __fn_print_hex_v_shift+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shr16
    JSR __rt_push
    LDA #<15
    STA __zpR
    LDA #>15
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_hex_v_digit
    LDA __zpR+1
    STA __fn_print_hex_v_digit+1
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L21
    JMP __L19
__L21:
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<48
    STA __zpR
    LDA #>48
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JMP __L20
__L19:
    LDA __fn_print_hex_v_digit
    STA __zpR
    LDA __fn_print_hex_v_digit+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    JSR __rt_push
    LDA #<65
    STA __zpR
    LDA #>65
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
__L20:
__L17:
    LDA __fn_print_hex_v_i
    STA __zpR
    LDA __fn_print_hex_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_print_hex_v_i
    LDA __zpR+1
    STA __fn_print_hex_v_i+1
    JMP __L15
__L16:
    RTS
 
; ---- function newline ---------------------------------------------
__fn_newline_frame:
__fn_newline_pushframe:
    RTS
 
__fn_newline_popframe:
    RTS
 
__fn_newline:
    LDA #<13
    STA __zpR
    LDA #>13
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    RTS
 
; ---- function point_sum ---------------------------------------------
__fn_point_sum_frame:
__fn_point_sum_v_p:
    .fill 2, 0
__fn_point_sum_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_point_sum_pushfr_loop:
    LDA __fn_point_sum_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_point_sum_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_point_sum_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_point_sum_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_point_sum_frame,Y
    INY
    CPY #2
    BNE __fn_point_sum_popfr_loop
    RTS
 
__fn_point_sum:
    LDA __fn_point_sum_v_p
    STA __zpR
    LDA __fn_point_sum_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDY #1
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_push
    LDA __fn_point_sum_v_p
    STA __zpR
    LDA __fn_point_sum_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function point_move ---------------------------------------------
__fn_point_move_frame:
__fn_point_move_v_p:
    .fill 2, 0
__fn_point_move_v_dx:
    .fill 2, 0
__fn_point_move_v_dy:
    .fill 2, 0
__fn_point_move_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_point_move_pushfr_loop:
    LDA __fn_point_move_frame,Y
    STA (__zpAP),Y
    INY
    CPY #6
    BNE __fn_point_move_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #6
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_point_move_popframe:
    SEC
    LDA __rt_csp
    SBC #6
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_point_move_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_point_move_frame,Y
    INY
    CPY #6
    BNE __fn_point_move_popfr_loop
    RTS
 
__fn_point_move:
    LDA __fn_point_move_v_p
    STA __zpR
    LDA __fn_point_move_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDY #1
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_push
    LDA __fn_point_move_v_dx
    STA __zpR
    LDA __fn_point_move_v_dx+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDY #1
    LDA __zpR+1
    STA (__zpAP),Y
    LDA __fn_point_move_v_p
    STA __zpR
    LDA __fn_point_move_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_push
    LDA __fn_point_move_v_dy
    STA __zpR
    LDA __fn_point_move_v_dy+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #2
    LDA __zpR
    STA (__zpAP),Y
    LDY #3
    LDA __zpR+1
    STA (__zpAP),Y
    RTS
 
; ---- function list_sum ---------------------------------------------
__fn_list_sum_frame:
__fn_list_sum_v_n:
    .fill 2, 0
__fn_list_sum_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_list_sum_pushfr_loop:
    LDA __fn_list_sum_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_list_sum_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_list_sum_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_list_sum_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_list_sum_frame,Y
    INY
    CPY #2
    BNE __fn_list_sum_popfr_loop
    RTS
 
__fn_list_sum:
    LDA __fn_list_sum_v_n
    STA __zpR
    LDA __fn_list_sum_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_eq16
    LDA __zpR
    ORA __zpR+1
    BNE __L24
    JMP __L22
__L24:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    RTS
    JMP __L23
__L22:
__L23:
    LDA __fn_list_sum_v_n
    STA __zpR
    LDA __fn_list_sum_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDY #1
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_push
    JSR __fn_list_sum_pushframe
    LDA __fn_list_sum_v_n
    STA __zpR
    LDA __fn_list_sum_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_list_sum_v_n
    LDA __zpR+1
    STA __fn_list_sum_v_n+1
    JSR __fn_list_sum
    JSR __fn_list_sum_popframe
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function list_length ---------------------------------------------
__fn_list_length_frame:
__fn_list_length_v_n:
    .fill 2, 0
__fn_list_length_v_count:
    .fill 2, 0
__fn_list_length_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_list_length_pushfr_loop:
    LDA __fn_list_length_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_list_length_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_list_length_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_list_length_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_list_length_frame,Y
    INY
    CPY #4
    BNE __fn_list_length_popfr_loop
    RTS
 
__fn_list_length:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_list_length_v_count
    LDA __zpR+1
    STA __fn_list_length_v_count+1
__L25:
    LDA __fn_list_length_v_n
    STA __zpR
    LDA __fn_list_length_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ne16
    LDA __zpR
    ORA __zpR+1
    BNE __L27
    JMP __L26
__L27:
    LDA __fn_list_length_v_count
    STA __zpR
    LDA __fn_list_length_v_count+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_list_length_v_count
    LDA __zpR+1
    STA __fn_list_length_v_count+1
    LDA __fn_list_length_v_n
    STA __zpR
    LDA __fn_list_length_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_list_length_v_n
    LDA __zpR+1
    STA __fn_list_length_v_n+1
    JMP __L25
__L26:
    LDA __fn_list_length_v_count
    STA __zpR
    LDA __fn_list_length_v_count+1
    STA __zpR+1
    RTS
    RTS
 
; ---- function main ---------------------------------------------
__fn_main_frame:
__fn_main_v_p:
    .fill 4, 0
__fn_main_v_pp:
    .fill 2, 0
__fn_main_v_n1:
    .fill 4, 0
__fn_main_v_n2:
    .fill 4, 0
__fn_main_v_n3:
    .fill 4, 0
__fn_main_v_i:
    .fill 2, 0
__fn_main_v_m:
    .fill 5, 0
__fn_main_v_px:
    .fill 2, 0
__fn_main_v_pe:
    .fill 2, 0
__fn_main_v_a:
    .fill 4, 0
__fn_main_v_b:
    .fill 4, 0
__fn_main_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_main_pushfr_loop:
    LDA __fn_main_frame,Y
    STA (__zpAP),Y
    INY
    CPY #37
    BNE __fn_main_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #37
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_main_popframe:
    SEC
    LDA __rt_csp
    SBC #37
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_main_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_main_frame,Y
    INY
    CPY #37
    BNE __fn_main_popfr_loop
    RTS
 
__fn_main:
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p
    LDA __zpR+1
    STA __fn_main_v_p+1
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_p+2
    LDA __zpR+1
    STA __fn_main_v_p+2+1
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_p+2
    STA __zpR
    LDA __fn_main_v_p+2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_main_v_p+2
    STA __zpR
    LDA __fn_main_v_p+2+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<__fn_main_v_p
    STA __zpR
    LDA #>__fn_main_v_p
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_pp
    LDA __zpR+1
    STA __fn_main_v_pp+1
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_pp
    STA __zpR
    LDA __fn_main_v_pp+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDY #1
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA __fn_main_v_pp
    STA __zpR
    LDA __fn_main_v_pp+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<30
    STA __zpR
    LDA #>30
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDY #1
    LDA __zpR+1
    STA (__zpAP),Y
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<__fn_main_v_p
    STA __zpR
    LDA #>__fn_main_v_p
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_px
    LDA __zpR+1
    STA __fn_main_v_px+1
    LDA __fn_main_v_px
    STA __zpR
    LDA __fn_main_v_px+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<99
    STA __zpR
    LDA #>99
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDY #1
    LDA __zpR+1
    STA (__zpAP),Y
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __g_g_origin
    LDA __zpR+1
    STA __g_g_origin+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __g_g_origin+2
    LDA __zpR+1
    STA __g_g_origin+2+1
    JSR __fn_print_int_pushframe
    LDA __g_g_origin
    STA __zpR
    LDA __g_g_origin+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_point_move_pushframe
    LDA #<__fn_main_v_p
    STA __zpR
    LDA #>__fn_main_v_p
    STA __zpR+1
    LDA __zpR
    STA __fn_point_move_v_p
    LDA __zpR+1
    STA __fn_point_move_v_p+1
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    LDA __zpR
    STA __fn_point_move_v_dx
    LDA __zpR+1
    STA __fn_point_move_v_dx+1
    LDA #<20
    STA __zpR
    LDA #>20
    STA __zpR+1
    LDA __zpR
    STA __fn_point_move_v_dy
    LDA __zpR+1
    STA __fn_point_move_v_dy+1
    JSR __fn_point_move
    JSR __fn_point_move_popframe
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_p
    STA __zpR
    LDA __fn_main_v_p+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_p+2
    STA __zpR
    LDA __fn_main_v_p+2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_point_sum_pushframe
    LDA #<__fn_main_v_p
    STA __zpR
    LDA #>__fn_main_v_p
    STA __zpR+1
    LDA __zpR
    STA __fn_point_sum_v_p
    LDA __zpR+1
    STA __fn_point_sum_v_p+1
    JSR __fn_point_sum
    JSR __fn_point_sum_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_i
    LDA __zpR+1
    STA __fn_main_v_i+1
__L28:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L31
    JMP __L29
__L31:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    LDA #4
    STA __zpR2
    LDA #0
    STA __zpR2+1
    JSR __rt_mul16
    CLC
    LDA __zpR
    ADC #<__g_g_pts
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_g_pts
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<10
    STA __zpR
    LDA #>10
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDY #1
    LDA __zpR+1
    STA (__zpAP),Y
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    LDA #4
    STA __zpR2
    LDA #0
    STA __zpR2+1
    JSR __rt_mul16
    CLC
    LDA __zpR
    ADC #<__g_g_pts
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_g_pts
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<100
    STA __zpR
    LDA #>100
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #2
    LDA __zpR
    STA (__zpAP),Y
    LDY #3
    LDA __zpR+1
    STA (__zpAP),Y
__L30:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_i
    LDA __zpR+1
    STA __fn_main_v_i+1
    JMP __L28
__L29:
    JSR __fn_print_int_pushframe
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    LDA #4
    STA __zpR2
    LDA #0
    STA __zpR2+1
    JSR __rt_mul16
    CLC
    LDA __zpR
    ADC #<__g_g_pts
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_g_pts
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDY #1
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    LDA #4
    STA __zpR2
    LDA #0
    STA __zpR2+1
    JSR __rt_mul16
    CLC
    LDA __zpR
    ADC #<__g_g_pts
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_g_pts
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA #4
    STA __zpR2
    LDA #0
    STA __zpR2+1
    JSR __rt_mul16
    CLC
    LDA __zpR
    ADC #<__g_g_pts
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_g_pts
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDY #1
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_push
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    LDA #4
    STA __zpR2
    LDA #0
    STA __zpR2+1
    JSR __rt_mul16
    CLC
    LDA __zpR
    ADC #<__g_g_pts
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_g_pts
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA #4
    STA __zpR2
    LDA #0
    STA __zpR2+1
    JSR __rt_mul16
    CLC
    LDA __zpR
    ADC #<__g_g_pts
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_g_pts
    STA __zpAP+1
    CLC
    LDA __zpAP
    ADC #2
    STA __zpR
    LDA __zpAP+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_pe
    LDA __zpR+1
    STA __fn_main_v_pe+1
    LDA __fn_main_v_pe
    STA __zpR
    LDA __fn_main_v_pe+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDA __zpAP
    STA __zpR
    LDA __zpAP+1
    STA __zpR+1
    JSR __rt_push
    LDA #<12345
    STA __zpR
    LDA #>12345
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDY #1
    LDA __zpR+1
    STA (__zpAP),Y
    JSR __fn_print_int_pushframe
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA #4
    STA __zpR2
    LDA #0
    STA __zpR2+1
    JSR __rt_mul16
    CLC
    LDA __zpR
    ADC #<__g_g_pts
    STA __zpAP
    LDA __zpR+1
    ADC #>__g_g_pts
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_n1
    LDA __zpR+1
    STA __fn_main_v_n1+1
    LDA #<__fn_main_v_n2
    STA __zpR
    LDA #>__fn_main_v_n2
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_n1+2
    LDA __zpR+1
    STA __fn_main_v_n1+2+1
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_n2
    LDA __zpR+1
    STA __fn_main_v_n2+1
    LDA #<__fn_main_v_n3
    STA __zpR
    LDA #>__fn_main_v_n3
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_n2+2
    LDA __zpR+1
    STA __fn_main_v_n2+2+1
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_n3
    LDA __zpR+1
    STA __fn_main_v_n3+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_n3+2
    LDA __zpR+1
    STA __fn_main_v_n3+2+1
    LDA #<__fn_main_v_n1
    STA __zpR
    LDA #>__fn_main_v_n1
    STA __zpR+1
    LDA __zpR
    STA __g_g_head
    LDA __zpR+1
    STA __g_g_head+1
    JSR __fn_print_int_pushframe
    JSR __fn_list_length_pushframe
    LDA __g_g_head
    STA __zpR
    LDA __g_g_head+1
    STA __zpR+1
    LDA __zpR
    STA __fn_list_length_v_n
    LDA __zpR+1
    STA __fn_list_length_v_n+1
    JSR __fn_list_length
    JSR __fn_list_length_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    JSR __fn_list_sum_pushframe
    LDA __g_g_head
    STA __zpR
    LDA __g_g_head+1
    STA __zpR+1
    LDA __zpR
    STA __fn_list_sum_v_n
    LDA __zpR+1
    STA __fn_list_sum_v_n+1
    JSR __fn_list_sum
    JSR __fn_list_sum_popframe
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<__fn_main_v_b
    STA __zpR
    LDA #>__fn_main_v_b
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_a
    LDA __zpR+1
    STA __fn_main_v_a+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_a+2
    LDA __zpR+1
    STA __fn_main_v_a+2+1
    LDA #<__fn_main_v_a
    STA __zpR
    LDA #>__fn_main_v_a
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_b
    LDA __zpR+1
    STA __fn_main_v_b+1
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_b+2
    LDA __zpR+1
    STA __fn_main_v_b+2+1
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_a
    STA __zpR
    LDA __fn_main_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_b
    STA __zpR
    LDA __fn_main_v_b+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_a
    STA __zpR
    LDA __fn_main_v_a+1
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDY #1
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #2
    LDA (__zpAP),Y
    STA __zpR
    LDY #3
    LDA (__zpAP),Y
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<90
    STA __zpR
    LDA #>90
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_m
    LDA #<1000
    STA __zpR
    LDA #>1000
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_m+1
    LDA __zpR+1
    STA __fn_main_v_m+1+1
    LDA #<__str_2
    STA __zpR
    LDA #>__str_2
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_m+3
    LDA __zpR+1
    STA __fn_main_v_m+3+1
    LDA __fn_main_v_m
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    JSR __fn_print_int_pushframe
    LDA __fn_main_v_m+1
    STA __zpR
    LDA __fn_main_v_m+1+1
    STA __zpR+1
    LDA __zpR
    STA __fn_print_int_v_n
    LDA __zpR+1
    STA __fn_print_int_v_n+1
    JSR __fn_print_int
    JSR __fn_print_int_popframe
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA __fn_main_v_m+3
    STA __zpR
    LDA __fn_main_v_m+3+1
    STA __zpR+1
    JSR __rt_puts
    JSR __fn_newline_pushframe
    JSR __fn_newline
    JSR __fn_newline_popframe
    LDA #<__str_3
    STA __zpR
    LDA #>__str_3
    STA __zpR+1
    JSR __rt_puts
    RTS
 
; ---- string literals (raw bytes; __rt_puts converts at print time) ----
__str_0:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,67,65,76,76,32,83,84,65,67,75,32
    .byte 79,86,69,82,70,76,79,87,13,40,82,69,67,85,82,83,73,79,78,32,84,79,79,32,68,69,69,80,44,32,79,82
    .byte 32,77,73,83,83,73,78,71,32,66,65,83,69,32,67,65,83,69,41,13,0
__str_1:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,69,88,80,82,69,83,83,73,79,78,32
    .byte 83,84,65,67,75,32,79,86,69,82,70,76,79,87,13,40,69,88,80,82,69,83,83,73,79,78,83,32,78,69,83,84
    .byte 69,68,32,84,79,79,32,68,69,69,80,76,89,32,65,67,82,79,83,83,32,82,69,67,85,82,83,73,79,78,41,13
    .byte 0
__str_2:
    .byte 104,105,0
__str_3:
    .byte 68,79,78,69,46,0
 
; ---- operand stack (128 16-bit slots, indexed by __rt_spidx) -------
__rt_stack:
    .fill 256, 0
; ---- call stack (4096 bytes; see codegen_stmt.c's emit_function() ---
; ---- and codegen_runtime.c's cstack-check comment for what this is)--
__rt_cstack:
    .fill 4096, 0
