; Generated by cc64 from examples/bounce_demo.c
; Assemble with: c64asm examples/bounce_demo.asm -o program.prg
 
; ---- zero page pseudo-registers ---------------------------------
; Only $02/$03 and $FB-$FE are used here. Per the KERNAL's own
; memory map, those are the ONLY zero-page bytes confirmed genuinely
; free: $F3/$F4 is the current-line-in-color-RAM pointer (touched by
; CHROUT itself when it colors a printed character) and $F5/$F6 is the
; keyboard-matrix-to-PETSCII conversion table pointer (touched by the
; keyboard scan on every background IRQ, ~60x/sec) - both looked like
; safe 'adjacent' bytes but are not; this bit us for real once already.
__zpAP = $02      ; effective-address pointer (2 bytes) - needs zero
                  ; page because it's used with (zp),Y indirection
__zpR  = $FB      ; primary register / return value (2 bytes)
__zpR2 = $FD      ; secondary operand register (2 bytes)
__CHROUT = $FFD2
 
.basic
    LDA #14           ; switch to the lower/upper character set - required
    JSR __CHROUT      ; for the PETSCII case mapping below to render as letters
                      ; (the default charset only has graphics past $C0)
    LDA #0
    STA __rt_spidx
    LDA #<__rt_cstack ; call-stack pointer starts at the base of its buffer -
    STA __rt_csp      ; see codegen_stmt.c's emit_function() for how each
    LDA #>__rt_cstack ; function's push/popframe routines use it to support
    STA __rt_csp+1    ; recursion despite locals/params living at fixed addresses
    JSR __fn_main
    RTS
 
; ---- runtime scratch storage (plain RAM, NOT zero page - only __zpAP
; needs (zp),Y indirection; these are always accessed directly) -------
__rt_spidx:
    .byte 0
__rt_csp:
    .fill 2, 0
__zpT1:
    .fill 2, 0
__zpT0:
    .fill 2, 0
__rt_pi_neg:
    .byte 0
__rt_pi_ndig:
    .byte 0
__rt_pbuf:
    .fill 5, 0
__rt_ph_lo:
    .byte 0
__rt_ph_byte_sv:
    .byte 0
 
; ---- runtime library -------------------------------------------
__rt_push:
    LDX __rt_spidx
    LDA __zpR
    STA __rt_stack,X
    LDA __zpR+1
    STA __rt_stack+1,X
    INX
    INX
    STX __rt_spidx
    BNE __rt_push_ok
    LDA #<__str_1
    STA __zpR
    LDA #>__str_1
    STA __zpR+1
    JSR __rt_puts
__rt_push_halt:
    JMP __rt_push_halt
__rt_push_ok:
    RTS
 
__rt_pop2:
    LDX __rt_spidx
    DEX
    DEX
    LDA __rt_stack,X
    STA __zpR2
    LDA __rt_stack+1,X
    STA __zpR2+1
    STX __rt_spidx
    RTS
 
__rt_cstack_check:
    TSX
    CPX #$20
    BCC __rt_csc_overflow
    LDA __rt_csp+1
    CMP #>(__rt_cstack+4096)
    BCC __rt_csc_ok
    BNE __rt_csc_overflow
    LDA __rt_csp
    CMP #<(__rt_cstack+4096)
    BCC __rt_csc_ok
    BEQ __rt_csc_ok
__rt_csc_overflow:
    LDA #<__str_0
    STA __zpR
    LDA #>__str_0
    STA __zpR+1
    JSR __rt_puts
__rt_csc_halt:
    JMP __rt_csc_halt
__rt_csc_ok:
    RTS
 
__rt_mul16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_mul16_loop:
    LSR __zpR+1
    ROR __zpR
    BCC __rt_mul16_noadd
    CLC
    LDA __zpT0
    ADC __zpR2
    STA __zpT0
    LDA __zpT0+1
    ADC __zpR2+1
    STA __zpT0+1
__rt_mul16_noadd:
    ASL __zpR2
    ROL __zpR2+1
    DEX
    BNE __rt_mul16_loop
    LDA __zpT0
    STA __zpR
    LDA __zpT0+1
    STA __zpR+1
    RTS
 
__rt_udiv16:
    LDA #0
    STA __zpT0
    STA __zpT0+1
    LDX #16
__rt_udiv16_loop:
    ASL __zpR2
    ROL __zpR2+1
    ROL __zpT0
    ROL __zpT0+1
    LDA __zpT0
    SEC
    SBC __zpR
    TAY
    LDA __zpT0+1
    SBC __zpR+1
    BCC __rt_udiv16_skip
    STA __zpT0+1
    STY __zpT0
    INC __zpR2
__rt_udiv16_skip:
    DEX
    BNE __rt_udiv16_loop
    RTS
 
__rt_neg_r2:
    SEC
    LDA #0
    SBC __zpR2
    TAX
    LDA #0
    SBC __zpR2+1
    STA __zpR2+1
    STX __zpR2
    RTS
 
__rt_neg_r:
    SEC
    LDA #0
    SBC __zpR
    TAX
    LDA #0
    SBC __zpR+1
    STA __zpR+1
    STX __zpR
    RTS
 
__rt_neg_t0:
    SEC
    LDA #0
    SBC __zpT0
    TAX
    LDA #0
    SBC __zpT0+1
    STA __zpT0+1
    STX __zpT0
    RTS
 
__rt_sdivmod16:
    LDA #0
    STA __zpT1
    STA __zpT1+1
    LDA __zpR2+1
    BPL __rt_sdm_d1
    JSR __rt_neg_r2
    INC __zpT1
__rt_sdm_d1:
    LDA __zpR+1
    BPL __rt_sdm_d2
    JSR __rt_neg_r
    INC __zpT1+1
__rt_sdm_d2:
    JSR __rt_udiv16
    LDA __zpT1
    EOR __zpT1+1
    AND #1
    BEQ __rt_sdm_qdone
    JSR __rt_neg_r2
__rt_sdm_qdone:
    LDA __zpT1
    BEQ __rt_sdm_rdone
    JSR __rt_neg_t0
__rt_sdm_rdone:
    RTS
 
__rt_eq16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_eq16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_eq16_ne
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_eq16_ne:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_ne16:
    LDA __zpR2
    CMP __zpR
    BNE __rt_ne16_ne
    LDA __zpR2+1
    CMP __zpR+1
    BNE __rt_ne16_ne
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ne16_ne:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_sub_r2r:
    SEC
    LDA __zpR2
    SBC __zpR
    LDA __zpR2+1
    SBC __zpR+1
    BVC __rt_sub_r2r_ok
    EOR #$80
__rt_sub_r2r_ok:
    RTS
 
__rt_sub_rr2:
    SEC
    LDA __zpR
    SBC __zpR2
    LDA __zpR+1
    SBC __zpR2+1
    BVC __rt_sub_rr2_ok
    EOR #$80
__rt_sub_rr2_ok:
    RTS
 
__rt_lt16:
    JSR __rt_sub_r2r
    BMI __rt_lt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_lt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ge16:
    JSR __rt_sub_r2r
    BPL __rt_ge16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_gt16:
    JSR __rt_sub_rr2
    BMI __rt_gt16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_gt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_le16:
    JSR __rt_sub_rr2
    BPL __rt_le16_t
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_le16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_shl16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shl16_loop:
    CPX #0
    BEQ __rt_shl16_done
    ASL __zpR
    ROL __zpR+1
    DEX
    JMP __rt_shl16_loop
__rt_shl16_done:
    RTS
 
__rt_shr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_shr16_loop:
    CPX #0
    BEQ __rt_shr16_done
    LDA __zpR+1
    CMP #$80
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_shr16_loop
__rt_shr16_done:
    RTS
 
__rt_ushr16:
    LDX __zpR
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
__rt_ushr16_loop:
    CPX #0
    BEQ __rt_ushr16_done
    CLC
    ROR __zpR+1
    ROR __zpR
    DEX
    JMP __rt_ushr16_loop
__rt_ushr16_done:
    RTS
 
__rt_topetscii:
    LDA __zpR
    CMP #$61
    BCC __rt_tp_notlower
    CMP #$7B
    BCS __rt_tp_notlower
    SEC
    SBC #$20
    STA __zpR
    JMP __rt_tp_done
__rt_tp_notlower:
    CMP #$41
    BCC __rt_tp_done
    CMP #$5B
    BCS __rt_tp_done
    CLC
    ADC #$80
    STA __zpR
__rt_tp_done:
    RTS
 
__rt_ult16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_ult16_t
    BNE __rt_ult16_f
    LDA __zpR2
    CMP __zpR
    BCC __rt_ult16_t
__rt_ult16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ult16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ugt16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ugt16_t
    BNE __rt_ugt16_f
    LDA __zpR
    CMP __zpR2
    BCC __rt_ugt16_t
__rt_ugt16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
__rt_ugt16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
 
__rt_ule16:
    LDA __zpR+1
    CMP __zpR2+1
    BCC __rt_ule16_f
    BNE __rt_ule16_t
    LDA __zpR
    CMP __zpR2
    BCC __rt_ule16_f
__rt_ule16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_ule16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_uge16:
    LDA __zpR2+1
    CMP __zpR+1
    BCC __rt_uge16_f
    BNE __rt_uge16_t
    LDA __zpR2
    CMP __zpR
    BCC __rt_uge16_f
__rt_uge16_t:
    LDA #1
    STA __zpR
    LDA #0
    STA __zpR+1
    RTS
__rt_uge16_f:
    LDA #0
    STA __zpR
    STA __zpR+1
    RTS
 
__rt_puts:
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
__rt_puts_loop:
    LDY #0
    LDA (__zpAP),Y
    BEQ __rt_puts_done
    STA __zpR
    JSR __rt_topetscii
    LDA __zpR
    JSR __CHROUT
    CLC
    LDA __zpAP
    ADC #1
    STA __zpAP
    LDA __zpAP+1
    ADC #0
    STA __zpAP+1
    JMP __rt_puts_loop
__rt_puts_done:
    RTS
 
__rt_putc:
    STA __zpR
    JSR __rt_topetscii
    LDA __zpR
    JMP __CHROUT
 
__rt_print_hex16:
    LDA __zpR
    STA __rt_ph_lo
    LDA __zpR+1
    JSR __rt_ph_byte
    LDA __rt_ph_lo
    JSR __rt_ph_byte
    RTS
__rt_ph_byte:
    STA __rt_ph_byte_sv
    LSR A
    LSR A
    LSR A
    LSR A
    JSR __rt_ph_nibble
    LDA __rt_ph_byte_sv
    AND #$0F
    JMP __rt_ph_nibble
__rt_ph_nibble:
    CMP #10
    BCC __rt_ph_digit
    CLC
    ADC #55
    JMP __rt_putc
__rt_ph_digit:
    CLC
    ADC #48
    JMP __rt_putc
 
__rt_print_int16:
    LDA #0
    STA __rt_pi_neg
    STA __rt_pi_ndig
    LDA __zpR+1
    BPL __rt_pi_notneg
    INC __rt_pi_neg
    SEC
    LDA #0
    SBC __zpR
    STA __zpR
    LDA #0
    SBC __zpR+1
    STA __zpR+1
__rt_pi_notneg:
    LDA __zpR
    ORA __zpR+1
    BNE __rt_pi_digloop_init
    LDA __rt_pi_neg
    BEQ __rt_pi_zero
    LDA #45
    JSR __rt_putc
__rt_pi_zero:
    LDA #48
    JMP __rt_putc
__rt_pi_digloop_init:
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    LDA #10
    STA __zpR
    LDA #0
    STA __zpR+1
__rt_pi_digloop:
    JSR __rt_sdivmod16
    LDX __rt_pi_ndig
    LDA __zpT0
    STA __rt_pbuf,X
    INC __rt_pi_ndig
    LDA __zpR2
    ORA __zpR2+1
    BNE __rt_pi_digloop
    LDA __rt_pi_neg
    BEQ __rt_pi_printloop
    LDA #45
    JSR __rt_putc
__rt_pi_printloop:
    DEC __rt_pi_ndig
    LDX __rt_pi_ndig
    LDA __rt_pbuf,X
    CLC
    ADC #48
    JSR __rt_putc
    LDA __rt_pi_ndig
    BNE __rt_pi_printloop
    RTS
 
__rt_print_uint16:
    LDA #0
    STA __rt_pi_ndig
    LDA __zpR
    ORA __zpR+1
    BNE __rt_pu_digloop_init
    LDA #48
    JMP __rt_putc
__rt_pu_digloop_init:
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    LDA #10
    STA __zpR
    LDA #0
    STA __zpR+1
__rt_pu_digloop:
    JSR __rt_udiv16
    LDX __rt_pi_ndig
    LDA __zpT0
    STA __rt_pbuf,X
    INC __rt_pi_ndig
    LDA __zpR2
    ORA __zpR2+1
    BNE __rt_pu_digloop
__rt_pu_printloop:
    DEC __rt_pi_ndig
    LDX __rt_pi_ndig
    LDA __rt_pbuf,X
    CLC
    ADC #48
    JSR __rt_putc
    LDA __rt_pi_ndig
    BNE __rt_pu_printloop
    RTS
 
; ---- global variables --------------------------------------------
 
; ---- function border_color ---------------------------------------------
__fn_border_color_frame:
__fn_border_color_v_c:
    .fill 2, 0
__fn_border_color_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_border_color_pushfr_loop:
    LDA __fn_border_color_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_border_color_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_border_color_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_border_color_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_border_color_frame,Y
    INY
    CPY #2
    BNE __fn_border_color_popfr_loop
    RTS
 
__fn_border_color:
    LDA #<53280
    STA __zpR
    LDA #>53280
    STA __zpR+1
    JSR __rt_push
    LDA __fn_border_color_v_c
    STA __zpR
    LDA __fn_border_color_v_c+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function background_color ---------------------------------------------
__fn_background_color_frame:
__fn_background_color_v_c:
    .fill 2, 0
__fn_background_color_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_background_color_pushfr_loop:
    LDA __fn_background_color_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_background_color_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_background_color_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_background_color_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_background_color_frame,Y
    INY
    CPY #2
    BNE __fn_background_color_popfr_loop
    RTS
 
__fn_background_color:
    LDA #<53281
    STA __zpR
    LDA #>53281
    STA __zpR+1
    JSR __rt_push
    LDA __fn_background_color_v_c
    STA __zpR
    LDA __fn_background_color_v_c+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function plot_char ---------------------------------------------
__fn_plot_char_frame:
__fn_plot_char_v_x:
    .fill 2, 0
__fn_plot_char_v_y:
    .fill 2, 0
__fn_plot_char_v_screen_code:
    .fill 2, 0
__fn_plot_char_v_color:
    .fill 2, 0
__fn_plot_char_v_offset:
    .fill 2, 0
__fn_plot_char_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_plot_char_pushfr_loop:
    LDA __fn_plot_char_frame,Y
    STA (__zpAP),Y
    INY
    CPY #10
    BNE __fn_plot_char_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #10
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_plot_char_popframe:
    SEC
    LDA __rt_csp
    SBC #10
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_plot_char_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_plot_char_frame,Y
    INY
    CPY #10
    BNE __fn_plot_char_popfr_loop
    RTS
 
__fn_plot_char:
    LDA __fn_plot_char_v_y
    STA __zpR
    LDA __fn_plot_char_v_y+1
    STA __zpR+1
    JSR __rt_push
    LDA #<40
    STA __zpR
    LDA #>40
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_push
    LDA __fn_plot_char_v_x
    STA __zpR
    LDA __fn_plot_char_v_x+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_plot_char_v_offset
    LDA __zpR+1
    STA __fn_plot_char_v_offset+1
    LDA #<1024
    STA __zpR
    LDA #>1024
    STA __zpR+1
    JSR __rt_push
    LDA __fn_plot_char_v_offset
    STA __zpR
    LDA __fn_plot_char_v_offset+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_plot_char_v_screen_code
    STA __zpR
    LDA __fn_plot_char_v_screen_code+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<55296
    STA __zpR
    LDA #>55296
    STA __zpR+1
    JSR __rt_push
    LDA __fn_plot_char_v_offset
    STA __zpR
    LDA __fn_plot_char_v_offset+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_plot_char_v_color
    STA __zpR
    LDA __fn_plot_char_v_color+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function clear_screen ---------------------------------------------
__fn_clear_screen_frame:
__fn_clear_screen_v_color:
    .fill 2, 0
__fn_clear_screen_v_i:
    .fill 2, 0
__fn_clear_screen_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_clear_screen_pushfr_loop:
    LDA __fn_clear_screen_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_clear_screen_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_clear_screen_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_clear_screen_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_clear_screen_frame,Y
    INY
    CPY #4
    BNE __fn_clear_screen_popfr_loop
    RTS
 
__fn_clear_screen:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_clear_screen_v_i
    LDA __zpR+1
    STA __fn_clear_screen_v_i+1
__L0:
    LDA __fn_clear_screen_v_i
    STA __zpR
    LDA __fn_clear_screen_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1000
    STA __zpR
    LDA #>1000
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L3
    JMP __L1
__L3:
    LDA #<1024
    STA __zpR
    LDA #>1024
    STA __zpR+1
    JSR __rt_push
    LDA __fn_clear_screen_v_i
    STA __zpR
    LDA __fn_clear_screen_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<32
    STA __zpR
    LDA #>32
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<55296
    STA __zpR
    LDA #>55296
    STA __zpR+1
    JSR __rt_push
    LDA __fn_clear_screen_v_i
    STA __zpR
    LDA __fn_clear_screen_v_i+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_clear_screen_v_color
    STA __zpR
    LDA __fn_clear_screen_v_color+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
__L2:
    LDA __fn_clear_screen_v_i
    STA __zpR
    LDA __fn_clear_screen_v_i+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #1
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_clear_screen_v_i
    LDA __zpR+1
    STA __fn_clear_screen_v_i+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    JMP __L0
__L1:
    RTS
 
; ---- function sprite_enable ---------------------------------------------
__fn_sprite_enable_frame:
__fn_sprite_enable_v_n:
    .fill 2, 0
__fn_sprite_enable_v_on:
    .fill 2, 0
__fn_sprite_enable_v_mask:
    .fill 2, 0
__fn_sprite_enable_v_v:
    .fill 2, 0
__fn_sprite_enable_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_enable_pushfr_loop:
    LDA __fn_sprite_enable_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sprite_enable_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_enable_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_enable_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_enable_frame,Y
    INY
    CPY #8
    BNE __fn_sprite_enable_popfr_loop
    RTS
 
__fn_sprite_enable:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_enable_v_n
    STA __zpR
    LDA __fn_sprite_enable_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    STA __fn_sprite_enable_v_mask
    LDA __zpR+1
    STA __fn_sprite_enable_v_mask+1
    LDA #<53269
    STA __zpR
    LDA #>53269
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_v
    LDA __zpR+1
    STA __fn_sprite_enable_v_v+1
    LDA __fn_sprite_enable_v_on
    STA __zpR
    LDA __fn_sprite_enable_v_on+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L6
    JMP __L4
__L6:
    LDA __fn_sprite_enable_v_v
    STA __zpR
    LDA __fn_sprite_enable_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_enable_v_mask
    STA __zpR
    LDA __fn_sprite_enable_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_v
    LDA __zpR+1
    STA __fn_sprite_enable_v_v+1
    JMP __L5
__L4:
    LDA __fn_sprite_enable_v_v
    STA __zpR
    LDA __fn_sprite_enable_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_enable_v_mask
    STA __zpR
    LDA __fn_sprite_enable_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_v
    LDA __zpR+1
    STA __fn_sprite_enable_v_v+1
__L5:
    LDA #<53269
    STA __zpR
    LDA #>53269
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_enable_v_v
    STA __zpR
    LDA __fn_sprite_enable_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_pos ---------------------------------------------
__fn_sprite_pos_frame:
__fn_sprite_pos_v_n:
    .fill 2, 0
__fn_sprite_pos_v_x:
    .fill 2, 0
__fn_sprite_pos_v_y:
    .fill 2, 0
__fn_sprite_pos_v_msb:
    .fill 2, 0
__fn_sprite_pos_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_pos_pushfr_loop:
    LDA __fn_sprite_pos_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sprite_pos_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_pos_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_pos_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_pos_frame,Y
    INY
    CPY #8
    BNE __fn_sprite_pos_popfr_loop
    RTS
 
__fn_sprite_pos:
    LDA #<53248
    STA __zpR
    LDA #>53248
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_n
    STA __zpR
    LDA __fn_sprite_pos_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_x
    STA __zpR
    LDA __fn_sprite_pos_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<53249
    STA __zpR
    LDA #>53249
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_n
    STA __zpR
    LDA __fn_sprite_pos_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_y
    STA __zpR
    LDA __fn_sprite_pos_v_y+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<53264
    STA __zpR
    LDA #>53264
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_msb
    LDA __zpR+1
    STA __fn_sprite_pos_v_msb+1
    LDA __fn_sprite_pos_v_x
    STA __zpR
    LDA __fn_sprite_pos_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_gt16
    LDA __zpR
    ORA __zpR+1
    BNE __L9
    JMP __L7
__L9:
    LDA __fn_sprite_pos_v_msb
    STA __zpR
    LDA __fn_sprite_pos_v_msb+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_n
    STA __zpR
    LDA __fn_sprite_pos_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_msb
    LDA __zpR+1
    STA __fn_sprite_pos_v_msb+1
    JMP __L8
__L7:
    LDA __fn_sprite_pos_v_msb
    STA __zpR
    LDA __fn_sprite_pos_v_msb+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_n
    STA __zpR
    LDA __fn_sprite_pos_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_msb
    LDA __zpR+1
    STA __fn_sprite_pos_v_msb+1
__L8:
    LDA #<53264
    STA __zpR
    LDA #>53264
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pos_v_msb
    STA __zpR
    LDA __fn_sprite_pos_v_msb+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_color ---------------------------------------------
__fn_sprite_color_frame:
__fn_sprite_color_v_n:
    .fill 2, 0
__fn_sprite_color_v_c:
    .fill 2, 0
__fn_sprite_color_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_color_pushfr_loop:
    LDA __fn_sprite_color_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_sprite_color_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_color_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_color_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_color_frame,Y
    INY
    CPY #4
    BNE __fn_sprite_color_popfr_loop
    RTS
 
__fn_sprite_color:
    LDA #<53287
    STA __zpR
    LDA #>53287
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_color_v_n
    STA __zpR
    LDA __fn_sprite_color_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_color_v_c
    STA __zpR
    LDA __fn_sprite_color_v_c+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_pointer ---------------------------------------------
__fn_sprite_pointer_frame:
__fn_sprite_pointer_v_n:
    .fill 2, 0
__fn_sprite_pointer_v_block:
    .fill 2, 0
__fn_sprite_pointer_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_pointer_pushfr_loop:
    LDA __fn_sprite_pointer_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_sprite_pointer_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_pointer_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_pointer_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_pointer_frame,Y
    INY
    CPY #4
    BNE __fn_sprite_pointer_popfr_loop
    RTS
 
__fn_sprite_pointer:
    LDA #<2040
    STA __zpR
    LDA #>2040
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pointer_v_n
    STA __zpR
    LDA __fn_sprite_pointer_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_pointer_v_block
    STA __zpR
    LDA __fn_sprite_pointer_v_block+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_multicolor ---------------------------------------------
__fn_sprite_multicolor_frame:
__fn_sprite_multicolor_v_n:
    .fill 2, 0
__fn_sprite_multicolor_v_on:
    .fill 2, 0
__fn_sprite_multicolor_v_mask:
    .fill 2, 0
__fn_sprite_multicolor_v_v:
    .fill 2, 0
__fn_sprite_multicolor_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_multicolor_pushfr_loop:
    LDA __fn_sprite_multicolor_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sprite_multicolor_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_multicolor_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_multicolor_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_multicolor_frame,Y
    INY
    CPY #8
    BNE __fn_sprite_multicolor_popfr_loop
    RTS
 
__fn_sprite_multicolor:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_multicolor_v_n
    STA __zpR
    LDA __fn_sprite_multicolor_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    STA __fn_sprite_multicolor_v_mask
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_mask+1
    LDA #<53276
    STA __zpR
    LDA #>53276
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_multicolor_v_v
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_v+1
    LDA __fn_sprite_multicolor_v_on
    STA __zpR
    LDA __fn_sprite_multicolor_v_on+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L12
    JMP __L10
__L12:
    LDA __fn_sprite_multicolor_v_v
    STA __zpR
    LDA __fn_sprite_multicolor_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_multicolor_v_mask
    STA __zpR
    LDA __fn_sprite_multicolor_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_multicolor_v_v
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_v+1
    JMP __L11
__L10:
    LDA __fn_sprite_multicolor_v_v
    STA __zpR
    LDA __fn_sprite_multicolor_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_multicolor_v_mask
    STA __zpR
    LDA __fn_sprite_multicolor_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_multicolor_v_v
    LDA __zpR+1
    STA __fn_sprite_multicolor_v_v+1
__L11:
    LDA #<53276
    STA __zpR
    LDA #>53276
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_multicolor_v_v
    STA __zpR
    LDA __fn_sprite_multicolor_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_shared_colors ---------------------------------------------
__fn_sprite_shared_colors_frame:
__fn_sprite_shared_colors_v_c1:
    .fill 2, 0
__fn_sprite_shared_colors_v_c3:
    .fill 2, 0
__fn_sprite_shared_colors_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_shared_colors_pushfr_loop:
    LDA __fn_sprite_shared_colors_frame,Y
    STA (__zpAP),Y
    INY
    CPY #4
    BNE __fn_sprite_shared_colors_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #4
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_shared_colors_popframe:
    SEC
    LDA __rt_csp
    SBC #4
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_shared_colors_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_shared_colors_frame,Y
    INY
    CPY #4
    BNE __fn_sprite_shared_colors_popfr_loop
    RTS
 
__fn_sprite_shared_colors:
    LDA #<53285
    STA __zpR
    LDA #>53285
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_shared_colors_v_c1
    STA __zpR
    LDA __fn_sprite_shared_colors_v_c1+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<53286
    STA __zpR
    LDA #>53286
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_shared_colors_v_c3
    STA __zpR
    LDA __fn_sprite_shared_colors_v_c3+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_expand ---------------------------------------------
__fn_sprite_expand_frame:
__fn_sprite_expand_v_n:
    .fill 2, 0
__fn_sprite_expand_v_x_on:
    .fill 2, 0
__fn_sprite_expand_v_y_on:
    .fill 2, 0
__fn_sprite_expand_v_mask:
    .fill 2, 0
__fn_sprite_expand_v_v:
    .fill 2, 0
__fn_sprite_expand_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_expand_pushfr_loop:
    LDA __fn_sprite_expand_frame,Y
    STA (__zpAP),Y
    INY
    CPY #10
    BNE __fn_sprite_expand_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #10
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_expand_popframe:
    SEC
    LDA __rt_csp
    SBC #10
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_expand_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_expand_frame,Y
    INY
    CPY #10
    BNE __fn_sprite_expand_popfr_loop
    RTS
 
__fn_sprite_expand:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_n
    STA __zpR
    LDA __fn_sprite_expand_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    STA __fn_sprite_expand_v_mask
    LDA __zpR+1
    STA __fn_sprite_expand_v_mask+1
    LDA #<53277
    STA __zpR
    LDA #>53277
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
    LDA __fn_sprite_expand_v_x_on
    STA __zpR
    LDA __fn_sprite_expand_v_x_on+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L15
    JMP __L13
__L15:
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_mask
    STA __zpR
    LDA __fn_sprite_expand_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
    JMP __L14
__L13:
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_mask
    STA __zpR
    LDA __fn_sprite_expand_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
__L14:
    LDA #<53277
    STA __zpR
    LDA #>53277
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<53271
    STA __zpR
    LDA #>53271
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
    LDA __fn_sprite_expand_v_y_on
    STA __zpR
    LDA __fn_sprite_expand_v_y_on+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L18
    JMP __L16
__L18:
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_mask
    STA __zpR
    LDA __fn_sprite_expand_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
    JMP __L17
__L16:
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_mask
    STA __zpR
    LDA __fn_sprite_expand_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_expand_v_v
    LDA __zpR+1
    STA __fn_sprite_expand_v_v+1
__L17:
    LDA #<53271
    STA __zpR
    LDA #>53271
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_expand_v_v
    STA __zpR
    LDA __fn_sprite_expand_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sprite_priority ---------------------------------------------
__fn_sprite_priority_frame:
__fn_sprite_priority_v_n:
    .fill 2, 0
__fn_sprite_priority_v_behind:
    .fill 2, 0
__fn_sprite_priority_v_mask:
    .fill 2, 0
__fn_sprite_priority_v_v:
    .fill 2, 0
__fn_sprite_priority_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_priority_pushfr_loop:
    LDA __fn_sprite_priority_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sprite_priority_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sprite_priority_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sprite_priority_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sprite_priority_frame,Y
    INY
    CPY #8
    BNE __fn_sprite_priority_popfr_loop
    RTS
 
__fn_sprite_priority:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_priority_v_n
    STA __zpR
    LDA __fn_sprite_priority_v_n+1
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    LDA __zpR
    STA __fn_sprite_priority_v_mask
    LDA __zpR+1
    STA __fn_sprite_priority_v_mask+1
    LDA #<53275
    STA __zpR
    LDA #>53275
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_priority_v_v
    LDA __zpR+1
    STA __fn_sprite_priority_v_v+1
    LDA __fn_sprite_priority_v_behind
    STA __zpR
    LDA __fn_sprite_priority_v_behind+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L21
    JMP __L19
__L21:
    LDA __fn_sprite_priority_v_v
    STA __zpR
    LDA __fn_sprite_priority_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_priority_v_mask
    STA __zpR
    LDA __fn_sprite_priority_v_mask+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_priority_v_v
    LDA __zpR+1
    STA __fn_sprite_priority_v_v+1
    JMP __L20
__L19:
    LDA __fn_sprite_priority_v_v
    STA __zpR
    LDA __fn_sprite_priority_v_v+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_priority_v_mask
    STA __zpR
    LDA __fn_sprite_priority_v_mask+1
    STA __zpR+1
    LDA __zpR
    EOR #$FF
    STA __zpR
    LDA __zpR+1
    EOR #$FF
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_priority_v_v
    LDA __zpR+1
    STA __fn_sprite_priority_v_v+1
__L20:
    LDA #<53275
    STA __zpR
    LDA #>53275
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sprite_priority_v_v
    STA __zpR
    LDA __fn_sprite_priority_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sid_volume ---------------------------------------------
__fn_sid_volume_frame:
__fn_sid_volume_v_v:
    .fill 2, 0
__fn_sid_volume_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_volume_pushfr_loop:
    LDA __fn_sid_volume_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_sid_volume_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sid_volume_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_volume_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sid_volume_frame,Y
    INY
    CPY #2
    BNE __fn_sid_volume_popfr_loop
    RTS
 
__fn_sid_volume:
    LDA #<54296
    STA __zpR
    LDA #>54296
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_volume_v_v
    STA __zpR
    LDA __fn_sid_volume_v_v+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sid_init ---------------------------------------------
__fn_sid_init_frame:
__fn_sid_init_pushframe:
    RTS
 
__fn_sid_init_popframe:
    RTS
 
__fn_sid_init:
    LDA #<54276
    STA __zpR
    LDA #>54276
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<54283
    STA __zpR
    LDA #>54283
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA #<54290
    STA __zpR
    LDA #>54290
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    JSR __fn_sid_volume_pushframe
    LDA #<15
    STA __zpR
    LDA #>15
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_volume_v_v
    LDA __zpR+1
    STA __fn_sid_volume_v_v+1
    JSR __fn_sid_volume
    JSR __fn_sid_volume_popframe
    RTS
 
; ---- function sid_freq ---------------------------------------------
__fn_sid_freq_frame:
__fn_sid_freq_v_n:
    .fill 2, 0
__fn_sid_freq_v_freq:
    .fill 2, 0
__fn_sid_freq_v_base:
    .fill 2, 0
__fn_sid_freq_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_freq_pushfr_loop:
    LDA __fn_sid_freq_frame,Y
    STA (__zpAP),Y
    INY
    CPY #6
    BNE __fn_sid_freq_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #6
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sid_freq_popframe:
    SEC
    LDA __rt_csp
    SBC #6
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_freq_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sid_freq_frame,Y
    INY
    CPY #6
    BNE __fn_sid_freq_popfr_loop
    RTS
 
__fn_sid_freq:
    LDA #<54272
    STA __zpR
    LDA #>54272
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_freq_v_n
    STA __zpR
    LDA __fn_sid_freq_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_freq_v_base
    LDA __zpR+1
    STA __fn_sid_freq_v_base+1
    LDA __fn_sid_freq_v_base
    STA __zpR
    LDA __fn_sid_freq_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_freq_v_freq
    STA __zpR
    LDA __fn_sid_freq_v_freq+1
    STA __zpR+1
    JSR __rt_push
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_sid_freq_v_base
    STA __zpR
    LDA __fn_sid_freq_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_freq_v_freq
    STA __zpR
    LDA __fn_sid_freq_v_freq+1
    STA __zpR+1
    JSR __rt_push
    LDA #<8
    STA __zpR
    LDA #>8
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ushr16
    JSR __rt_push
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sid_pulse_width ---------------------------------------------
__fn_sid_pulse_width_frame:
__fn_sid_pulse_width_v_n:
    .fill 2, 0
__fn_sid_pulse_width_v_width:
    .fill 2, 0
__fn_sid_pulse_width_v_base:
    .fill 2, 0
__fn_sid_pulse_width_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_pulse_width_pushfr_loop:
    LDA __fn_sid_pulse_width_frame,Y
    STA (__zpAP),Y
    INY
    CPY #6
    BNE __fn_sid_pulse_width_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #6
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sid_pulse_width_popframe:
    SEC
    LDA __rt_csp
    SBC #6
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_pulse_width_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sid_pulse_width_frame,Y
    INY
    CPY #6
    BNE __fn_sid_pulse_width_popfr_loop
    RTS
 
__fn_sid_pulse_width:
    LDA #<54272
    STA __zpR
    LDA #>54272
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_pulse_width_v_n
    STA __zpR
    LDA __fn_sid_pulse_width_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_pulse_width_v_base
    LDA __zpR+1
    STA __fn_sid_pulse_width_v_base+1
    LDA __fn_sid_pulse_width_v_base
    STA __zpR
    LDA __fn_sid_pulse_width_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_pulse_width_v_width
    STA __zpR
    LDA __fn_sid_pulse_width_v_width+1
    STA __zpR+1
    JSR __rt_push
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_sid_pulse_width_v_base
    STA __zpR
    LDA __fn_sid_pulse_width_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_pulse_width_v_width
    STA __zpR
    LDA __fn_sid_pulse_width_v_width+1
    STA __zpR+1
    JSR __rt_push
    LDA #<8
    STA __zpR
    LDA #>8
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ushr16
    JSR __rt_push
    LDA #<15
    STA __zpR
    LDA #>15
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    AND __zpR
    STA __zpR
    LDA __zpR2+1
    AND __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sid_adsr ---------------------------------------------
__fn_sid_adsr_frame:
__fn_sid_adsr_v_n:
    .fill 2, 0
__fn_sid_adsr_v_attack:
    .fill 2, 0
__fn_sid_adsr_v_decay:
    .fill 2, 0
__fn_sid_adsr_v_sustain:
    .fill 2, 0
__fn_sid_adsr_v_release:
    .fill 2, 0
__fn_sid_adsr_v_base:
    .fill 2, 0
__fn_sid_adsr_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_adsr_pushfr_loop:
    LDA __fn_sid_adsr_frame,Y
    STA (__zpAP),Y
    INY
    CPY #12
    BNE __fn_sid_adsr_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #12
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sid_adsr_popframe:
    SEC
    LDA __rt_csp
    SBC #12
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_adsr_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sid_adsr_frame,Y
    INY
    CPY #12
    BNE __fn_sid_adsr_popfr_loop
    RTS
 
__fn_sid_adsr:
    LDA #<54272
    STA __zpR
    LDA #>54272
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_adsr_v_n
    STA __zpR
    LDA __fn_sid_adsr_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_adsr_v_base
    LDA __zpR+1
    STA __fn_sid_adsr_v_base+1
    LDA __fn_sid_adsr_v_base
    STA __zpR
    LDA __fn_sid_adsr_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA #<5
    STA __zpR
    LDA #>5
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_adsr_v_attack
    STA __zpR
    LDA __fn_sid_adsr_v_attack+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    JSR __rt_push
    LDA __fn_sid_adsr_v_decay
    STA __zpR
    LDA __fn_sid_adsr_v_decay+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_sid_adsr_v_base
    STA __zpR
    LDA __fn_sid_adsr_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA #<6
    STA __zpR
    LDA #>6
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_adsr_v_sustain
    STA __zpR
    LDA __fn_sid_adsr_v_sustain+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_shl16
    JSR __rt_push
    LDA __fn_sid_adsr_v_release
    STA __zpR
    LDA __fn_sid_adsr_v_release+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sid_gate ---------------------------------------------
__fn_sid_gate_frame:
__fn_sid_gate_v_n:
    .fill 2, 0
__fn_sid_gate_v_waveform:
    .fill 2, 0
__fn_sid_gate_v_gate:
    .fill 2, 0
__fn_sid_gate_v_base:
    .fill 2, 0
__fn_sid_gate_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_gate_pushfr_loop:
    LDA __fn_sid_gate_frame,Y
    STA (__zpAP),Y
    INY
    CPY #8
    BNE __fn_sid_gate_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #8
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sid_gate_popframe:
    SEC
    LDA __rt_csp
    SBC #8
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_gate_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sid_gate_frame,Y
    INY
    CPY #8
    BNE __fn_sid_gate_popfr_loop
    RTS
 
__fn_sid_gate:
    LDA #<54272
    STA __zpR
    LDA #>54272
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_gate_v_n
    STA __zpR
    LDA __fn_sid_gate_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_gate_v_base
    LDA __zpR+1
    STA __fn_sid_gate_v_base+1
    LDA __fn_sid_gate_v_gate
    STA __zpR
    LDA __fn_sid_gate_v_gate+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L24
    JMP __L22
__L24:
    LDA __fn_sid_gate_v_base
    STA __zpR
    LDA __fn_sid_gate_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_gate_v_waveform
    STA __zpR
    LDA __fn_sid_gate_v_waveform+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    ORA __zpR
    STA __zpR
    LDA __zpR2+1
    ORA __zpR+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    JMP __L23
__L22:
    LDA __fn_sid_gate_v_base
    STA __zpR
    LDA __fn_sid_gate_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_gate_v_waveform
    STA __zpR
    LDA __fn_sid_gate_v_waveform+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
__L23:
    RTS
 
; ---- function sid_silence ---------------------------------------------
__fn_sid_silence_frame:
__fn_sid_silence_v_n:
    .fill 2, 0
__fn_sid_silence_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_silence_pushfr_loop:
    LDA __fn_sid_silence_frame,Y
    STA (__zpAP),Y
    INY
    CPY #2
    BNE __fn_sid_silence_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #2
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sid_silence_popframe:
    SEC
    LDA __rt_csp
    SBC #2
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_silence_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sid_silence_frame,Y
    INY
    CPY #2
    BNE __fn_sid_silence_popfr_loop
    RTS
 
__fn_sid_silence:
    LDA #<54272
    STA __zpR
    LDA #>54272
    STA __zpR+1
    JSR __rt_push
    LDA __fn_sid_silence_v_n
    STA __zpR
    LDA __fn_sid_silence_v_n+1
    STA __zpR+1
    JSR __rt_push
    LDA #<7
    STA __zpR
    LDA #>7
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<4
    STA __zpR
    LDA #>4
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    RTS
 
; ---- function sid_play ---------------------------------------------
__fn_sid_play_frame:
__fn_sid_play_v_n:
    .fill 2, 0
__fn_sid_play_v_freq:
    .fill 2, 0
__fn_sid_play_v_waveform:
    .fill 2, 0
__fn_sid_play_v_attack:
    .fill 2, 0
__fn_sid_play_v_decay:
    .fill 2, 0
__fn_sid_play_v_sustain:
    .fill 2, 0
__fn_sid_play_v_release:
    .fill 2, 0
__fn_sid_play_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_play_pushfr_loop:
    LDA __fn_sid_play_frame,Y
    STA (__zpAP),Y
    INY
    CPY #14
    BNE __fn_sid_play_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #14
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_sid_play_popframe:
    SEC
    LDA __rt_csp
    SBC #14
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_sid_play_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_sid_play_frame,Y
    INY
    CPY #14
    BNE __fn_sid_play_popfr_loop
    RTS
 
__fn_sid_play:
    JSR __fn_sid_gate_pushframe
    LDA __fn_sid_play_v_n
    STA __zpR
    LDA __fn_sid_play_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_gate_v_n
    LDA __zpR+1
    STA __fn_sid_gate_v_n+1
    LDA __fn_sid_play_v_waveform
    STA __zpR
    LDA __fn_sid_play_v_waveform+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_gate_v_waveform
    LDA __zpR+1
    STA __fn_sid_gate_v_waveform+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_gate_v_gate
    LDA __zpR+1
    STA __fn_sid_gate_v_gate+1
    JSR __fn_sid_gate
    JSR __fn_sid_gate_popframe
    JSR __fn_sid_freq_pushframe
    LDA __fn_sid_play_v_n
    STA __zpR
    LDA __fn_sid_play_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_freq_v_n
    LDA __zpR+1
    STA __fn_sid_freq_v_n+1
    LDA __fn_sid_play_v_freq
    STA __zpR
    LDA __fn_sid_play_v_freq+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_freq_v_freq
    LDA __zpR+1
    STA __fn_sid_freq_v_freq+1
    JSR __fn_sid_freq
    JSR __fn_sid_freq_popframe
    JSR __fn_sid_adsr_pushframe
    LDA __fn_sid_play_v_n
    STA __zpR
    LDA __fn_sid_play_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_adsr_v_n
    LDA __zpR+1
    STA __fn_sid_adsr_v_n+1
    LDA __fn_sid_play_v_attack
    STA __zpR
    LDA __fn_sid_play_v_attack+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_adsr_v_attack
    LDA __zpR+1
    STA __fn_sid_adsr_v_attack+1
    LDA __fn_sid_play_v_decay
    STA __zpR
    LDA __fn_sid_play_v_decay+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_adsr_v_decay
    LDA __zpR+1
    STA __fn_sid_adsr_v_decay+1
    LDA __fn_sid_play_v_sustain
    STA __zpR
    LDA __fn_sid_play_v_sustain+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_adsr_v_sustain
    LDA __zpR+1
    STA __fn_sid_adsr_v_sustain+1
    LDA __fn_sid_play_v_release
    STA __zpR
    LDA __fn_sid_play_v_release+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_adsr_v_release
    LDA __zpR+1
    STA __fn_sid_adsr_v_release+1
    JSR __fn_sid_adsr
    JSR __fn_sid_adsr_popframe
    JSR __fn_sid_gate_pushframe
    LDA __fn_sid_play_v_n
    STA __zpR
    LDA __fn_sid_play_v_n+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_gate_v_n
    LDA __zpR+1
    STA __fn_sid_gate_v_n+1
    LDA __fn_sid_play_v_waveform
    STA __zpR
    LDA __fn_sid_play_v_waveform+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_gate_v_waveform
    LDA __zpR+1
    STA __fn_sid_gate_v_waveform+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_gate_v_gate
    LDA __zpR+1
    STA __fn_sid_gate_v_gate+1
    JSR __fn_sid_gate
    JSR __fn_sid_gate_popframe
    RTS
 
; ---- function main ---------------------------------------------
__fn_main_frame:
__fn_main_v_i:
    .fill 2, 0
__fn_main_v_rowval:
    .fill 2, 0
__fn_main_v_base:
    .fill 2, 0
__fn_main_v_x:
    .fill 2, 0
__fn_main_v_y:
    .fill 2, 0
__fn_main_v_xdir:
    .fill 2, 0
__fn_main_v_ydir:
    .fill 2, 0
__fn_main_v_bounced:
    .fill 2, 0
__fn_main_pushframe:
    LDA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_main_pushfr_loop:
    LDA __fn_main_frame,Y
    STA (__zpAP),Y
    INY
    CPY #16
    BNE __fn_main_pushfr_loop
    CLC
    LDA __rt_csp
    ADC #16
    STA __rt_csp
    LDA __rt_csp+1
    ADC #0
    STA __rt_csp+1
    JMP __rt_cstack_check
 
__fn_main_popframe:
    SEC
    LDA __rt_csp
    SBC #16
    STA __rt_csp
    STA __zpAP
    LDA __rt_csp+1
    SBC #0
    STA __rt_csp+1
    STA __zpAP+1
    LDY #0
__fn_main_popfr_loop:
    LDA (__zpAP),Y
    STA __fn_main_frame,Y
    INY
    CPY #16
    BNE __fn_main_popfr_loop
    RTS
 
__fn_main:
    LDA #<15872
    STA __zpR
    LDA #>15872
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_base
    LDA __zpR+1
    STA __fn_main_v_base+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_i
    LDA __zpR+1
    STA __fn_main_v_i+1
__L25:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<21
    STA __zpR
    LDA #>21
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_lt16
    LDA __zpR
    ORA __zpR+1
    BNE __L28
    JMP __L26
__L28:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    LDA __zpR
    CMP #0
    BNE __L36
    LDA __zpR+1
    CMP #0
    BNE __L36
    JMP __L30
__L36:
    LDA __zpR
    CMP #19
    BNE __L37
    LDA __zpR+1
    CMP #0
    BNE __L37
    JMP __L31
__L37:
    LDA __zpR
    CMP #1
    BNE __L38
    LDA __zpR+1
    CMP #0
    BNE __L38
    JMP __L32
__L38:
    LDA __zpR
    CMP #18
    BNE __L39
    LDA __zpR+1
    CMP #0
    BNE __L39
    JMP __L33
__L39:
    LDA __zpR
    CMP #20
    BNE __L40
    LDA __zpR+1
    CMP #0
    BNE __L40
    JMP __L34
__L40:
    JMP __L35
__L30:
__L31:
    LDA #<60
    STA __zpR
    LDA #>60
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_rowval
    LDA __zpR+1
    STA __fn_main_v_rowval+1
    JMP __L29
__L32:
__L33:
    LDA #<126
    STA __zpR
    LDA #>126
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_rowval
    LDA __zpR+1
    STA __fn_main_v_rowval+1
    JMP __L29
__L34:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_rowval
    LDA __zpR+1
    STA __fn_main_v_rowval+1
    JMP __L29
__L35:
    LDA #<255
    STA __zpR
    LDA #>255
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_rowval
    LDA __zpR+1
    STA __fn_main_v_rowval+1
    JMP __L29
__L29:
    LDA __fn_main_v_base
    STA __zpR
    LDA __fn_main_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_main_v_rowval
    STA __zpR
    LDA __fn_main_v_rowval+1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_main_v_base
    STA __zpR
    LDA __fn_main_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    LDA __fn_main_v_base
    STA __zpR
    LDA __fn_main_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    JSR __rt_push
    LDA #<3
    STA __zpR
    LDA #>3
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_mul16
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<2
    STA __zpR
    LDA #>2
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    JSR __rt_push
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
__L27:
    LDA __fn_main_v_i
    STA __zpR
    LDA __fn_main_v_i+1
    STA __zpR+1
    LDA __zpR
    STA __zpR2
    LDA __zpR+1
    STA __zpR2+1
    CLC
    LDA __zpR
    ADC #1
    STA __zpR
    LDA __zpR+1
    ADC #0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_i
    LDA __zpR+1
    STA __fn_main_v_i+1
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    JMP __L25
__L26:
    LDA #<204
    STA __zpR
    LDA #>204
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    LDA __zpR2
    STA __zpAP
    LDA __zpR2+1
    STA __zpAP+1
    LDY #0
    LDA __zpR
    STA (__zpAP),Y
    JSR __fn_border_color_pushframe
    LDA #<6
    STA __zpR
    LDA #>6
    STA __zpR+1
    LDA __zpR
    STA __fn_border_color_v_c
    LDA __zpR+1
    STA __fn_border_color_v_c+1
    JSR __fn_border_color
    JSR __fn_border_color_popframe
    JSR __fn_background_color_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_background_color_v_c
    LDA __zpR+1
    STA __fn_background_color_v_c+1
    JSR __fn_background_color
    JSR __fn_background_color_popframe
    JSR __fn_clear_screen_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_clear_screen_v_color
    LDA __zpR+1
    STA __fn_clear_screen_v_color+1
    JSR __fn_clear_screen
    JSR __fn_clear_screen_popframe
    JSR __fn_sprite_pointer_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pointer_v_n
    LDA __zpR+1
    STA __fn_sprite_pointer_v_n+1
    LDA __fn_main_v_base
    STA __zpR
    LDA __fn_main_v_base+1
    STA __zpR+1
    JSR __rt_push
    LDA #<64
    STA __zpR
    LDA #>64
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_sdivmod16
    LDA __zpR2
    STA __zpR
    LDA __zpR2+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pointer_v_block
    LDA __zpR+1
    STA __fn_sprite_pointer_v_block+1
    JSR __fn_sprite_pointer
    JSR __fn_sprite_pointer_popframe
    JSR __fn_sprite_color_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_color_v_n
    LDA __zpR+1
    STA __fn_sprite_color_v_n+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_color_v_c
    LDA __zpR+1
    STA __fn_sprite_color_v_c+1
    JSR __fn_sprite_color
    JSR __fn_sprite_color_popframe
    LDA #<24
    STA __zpR
    LDA #>24
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_x
    LDA __zpR+1
    STA __fn_main_v_x+1
    LDA #<50
    STA __zpR
    LDA #>50
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_y
    LDA __zpR+1
    STA __fn_main_v_y+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_xdir
    LDA __zpR+1
    STA __fn_main_v_xdir+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_ydir
    LDA __zpR+1
    STA __fn_main_v_ydir+1
    JSR __fn_sprite_pos_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_n
    LDA __zpR+1
    STA __fn_sprite_pos_v_n+1
    LDA __fn_main_v_x
    STA __zpR
    LDA __fn_main_v_x+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_x
    LDA __zpR+1
    STA __fn_sprite_pos_v_x+1
    LDA __fn_main_v_y
    STA __zpR
    LDA __fn_main_v_y+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_y
    LDA __zpR+1
    STA __fn_sprite_pos_v_y+1
    JSR __fn_sprite_pos
    JSR __fn_sprite_pos_popframe
    JSR __fn_sprite_enable_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_n
    LDA __zpR+1
    STA __fn_sprite_enable_v_n+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_enable_v_on
    LDA __zpR+1
    STA __fn_sprite_enable_v_on+1
    JSR __fn_sprite_enable
    JSR __fn_sprite_enable_popframe
    JSR __fn_sid_init_pushframe
    JSR __fn_sid_init
    JSR __fn_sid_init_popframe
__L41:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L43
    JMP __L42
__L43:
__L44:
    LDA #<53266
    STA __zpR
    LDA #>53266
    STA __zpR+1
    LDA __zpR
    STA __zpAP
    LDA __zpR+1
    STA __zpAP+1
    LDY #0
    LDA (__zpAP),Y
    STA __zpR
    LDA #0
    STA __zpR+1
    JSR __rt_push
    LDA #<251
    STA __zpR
    LDA #>251
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ne16
    LDA __zpR
    ORA __zpR+1
    BNE __L46
    JMP __L45
__L46:
    JMP __L44
__L45:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_bounced
    LDA __zpR+1
    STA __fn_main_v_bounced+1
    LDA __fn_main_v_xdir
    STA __zpR
    LDA __fn_main_v_xdir+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L49
    JMP __L47
__L49:
    LDA __fn_main_v_x
    STA __zpR
    LDA __fn_main_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_x
    LDA __zpR+1
    STA __fn_main_v_x+1
    LDA __fn_main_v_x
    STA __zpR
    LDA __fn_main_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<320
    STA __zpR
    LDA #>320
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ge16
    LDA __zpR
    ORA __zpR+1
    BNE __L52
    JMP __L50
__L52:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_xdir
    LDA __zpR+1
    STA __fn_main_v_xdir+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_bounced
    LDA __zpR+1
    STA __fn_main_v_bounced+1
    JMP __L51
__L50:
__L51:
    JMP __L48
__L47:
    LDA __fn_main_v_x
    STA __zpR
    LDA __fn_main_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_main_v_x
    LDA __zpR+1
    STA __fn_main_v_x+1
    LDA __fn_main_v_x
    STA __zpR
    LDA __fn_main_v_x+1
    STA __zpR+1
    JSR __rt_push
    LDA #<24
    STA __zpR
    LDA #>24
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_le16
    LDA __zpR
    ORA __zpR+1
    BNE __L55
    JMP __L53
__L55:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_xdir
    LDA __zpR+1
    STA __fn_main_v_xdir+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_bounced
    LDA __zpR+1
    STA __fn_main_v_bounced+1
    JMP __L54
__L53:
__L54:
__L48:
    LDA __fn_main_v_ydir
    STA __zpR
    LDA __fn_main_v_ydir+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L58
    JMP __L56
__L58:
    LDA __fn_main_v_y
    STA __zpR
    LDA __fn_main_v_y+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    CLC
    LDA __zpR2
    ADC __zpR
    STA __zpR
    LDA __zpR2+1
    ADC __zpR+1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_y
    LDA __zpR+1
    STA __fn_main_v_y+1
    LDA __fn_main_v_y
    STA __zpR
    LDA __fn_main_v_y+1
    STA __zpR+1
    JSR __rt_push
    LDA #<229
    STA __zpR
    LDA #>229
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_ge16
    LDA __zpR
    ORA __zpR+1
    BNE __L61
    JMP __L59
__L61:
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_ydir
    LDA __zpR+1
    STA __fn_main_v_ydir+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_bounced
    LDA __zpR+1
    STA __fn_main_v_bounced+1
    JMP __L60
__L59:
__L60:
    JMP __L57
__L56:
    LDA __fn_main_v_y
    STA __zpR
    LDA __fn_main_v_y+1
    STA __zpR+1
    JSR __rt_push
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    JSR __rt_pop2
    SEC
    LDA __zpR2
    SBC __zpR
    STA __zpR2
    LDA __zpR2+1
    SBC __zpR+1
    STA __zpR+1
    LDA __zpR2
    STA __zpR
    LDA __zpR
    STA __fn_main_v_y
    LDA __zpR+1
    STA __fn_main_v_y+1
    LDA __fn_main_v_y
    STA __zpR
    LDA __fn_main_v_y+1
    STA __zpR+1
    JSR __rt_push
    LDA #<50
    STA __zpR
    LDA #>50
    STA __zpR+1
    JSR __rt_pop2
    JSR __rt_le16
    LDA __zpR
    ORA __zpR+1
    BNE __L64
    JMP __L62
__L64:
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_ydir
    LDA __zpR+1
    STA __fn_main_v_ydir+1
    LDA #<1
    STA __zpR
    LDA #>1
    STA __zpR+1
    LDA __zpR
    STA __fn_main_v_bounced
    LDA __zpR+1
    STA __fn_main_v_bounced+1
    JMP __L63
__L62:
__L63:
__L57:
    JSR __fn_sprite_pos_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_n
    LDA __zpR+1
    STA __fn_sprite_pos_v_n+1
    LDA __fn_main_v_x
    STA __zpR
    LDA __fn_main_v_x+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_x
    LDA __zpR+1
    STA __fn_sprite_pos_v_x+1
    LDA __fn_main_v_y
    STA __zpR
    LDA __fn_main_v_y+1
    STA __zpR+1
    LDA __zpR
    STA __fn_sprite_pos_v_y
    LDA __zpR+1
    STA __fn_sprite_pos_v_y+1
    JSR __fn_sprite_pos
    JSR __fn_sprite_pos_popframe
    LDA __fn_main_v_bounced
    STA __zpR
    LDA __fn_main_v_bounced+1
    STA __zpR+1
    LDA __zpR
    ORA __zpR+1
    BNE __L67
    JMP __L65
__L67:
    JSR __fn_sid_play_pushframe
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_play_v_n
    LDA __zpR+1
    STA __fn_sid_play_v_n+1
    LDA #<6144
    STA __zpR
    LDA #>6144
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_play_v_freq
    LDA __zpR+1
    STA __fn_sid_play_v_freq+1
    LDA #<128
    STA __zpR
    LDA #>128
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_play_v_waveform
    LDA __zpR+1
    STA __fn_sid_play_v_waveform+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_play_v_attack
    LDA __zpR+1
    STA __fn_sid_play_v_attack+1
    LDA #<6
    STA __zpR
    LDA #>6
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_play_v_decay
    LDA __zpR+1
    STA __fn_sid_play_v_decay+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_play_v_sustain
    LDA __zpR+1
    STA __fn_sid_play_v_sustain+1
    LDA #<0
    STA __zpR
    LDA #>0
    STA __zpR+1
    LDA __zpR
    STA __fn_sid_play_v_release
    LDA __zpR+1
    STA __fn_sid_play_v_release+1
    JSR __fn_sid_play
    JSR __fn_sid_play_popframe
    JMP __L66
__L65:
__L66:
    JMP __L41
__L42:
    RTS
 
; ---- string literals (raw bytes; __rt_puts converts at print time) ----
__str_0:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,67,65,76,76,32,83,84,65,67,75,32
    .byte 79,86,69,82,70,76,79,87,13,40,82,69,67,85,82,83,73,79,78,32,84,79,79,32,68,69,69,80,44,32,79,82
    .byte 32,77,73,83,83,73,78,71,32,66,65,83,69,32,67,65,83,69,41,13,0
__str_1:
    .byte 13,67,67,54,52,32,82,85,78,84,73,77,69,32,69,82,82,79,82,58,32,69,88,80,82,69,83,83,73,79,78,32
    .byte 83,84,65,67,75,32,79,86,69,82,70,76,79,87,13,40,69,88,80,82,69,83,83,73,79,78,83,32,78,69,83,84
    .byte 69,68,32,84,79,79,32,68,69,69,80,76,89,32,65,67,82,79,83,83,32,82,69,67,85,82,83,73,79,78,41,13
    .byte 0
 
; ---- operand stack (128 16-bit slots, indexed by __rt_spidx) -------
__rt_stack:
    .fill 256, 0
; ---- call stack (4096 bytes; see codegen_stmt.c's emit_function() ---
; ---- and codegen_runtime.c's cstack-check comment for what this is)--
__rt_cstack:
    .fill 4096, 0
