/*
 * main.c - the command-line driver. Reads the input file, then runs
 * the whole pipeline described in cc64.h's overview: lex -> pass_a
 * (scan signatures) -> emit the fixed runtime library -> pass_b
 * (parse each function body, generating its code as it goes) -> emit
 * string literal data -> done.
 *
 * This file is intentionally thin. Almost everything it does is call
 * one function from another module in the order the pipeline
 * requires; the actual work all happens in those modules. Reading
 * main() top to bottom is a reasonable way to see the whole
 * compilation process at a glance before diving into any one phase.
 */

#include "cc64.h"

static void usage(const char *prog) {
    fprintf(stderr, "cc64 - a minimal C compiler for the Commodore 64 (6502 target)\n\n");
    fprintf(stderr, "Usage: %s <input.c> -o <output.asm> [-I dir ...]\n", prog);
}

/* Best-effort default for `#include <...>`: if cc64 was invoked with
 * a path (like the `./cc64` this project's own docs and build.sh
 * always use), add a "lib" directory next to the binary - which is
 * exactly where this project's own lib/ lives, so `#include <string.h>`
 * works out of the box with no -I needed. If cc64 was found via PATH
 * (argv[0] has no '/' in it), there's no portable, C99-only way to
 * recover the binary's real location, so this is silently skipped;
 * -I (or running from the project directory) still works either way. */
static void add_default_lib_dir(const char *argv0) {
    const char *slash = strrchr(argv0, '/');
    if (!slash) return;
    size_t dirlen = (size_t)(slash - argv0);
    char *dir = xmalloc(dirlen + 5); /* + "/lib" + NUL */
    memcpy(dir, argv0, dirlen);
    memcpy(dir + dirlen, "/lib", 5);
    add_include_dir(dir);
    free(dir);
}

int main(int argc, char **argv) {
    const char *input_path = NULL, *output_path = NULL;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-o") == 0) {
            if (i + 1 >= argc) { usage(argv[0]); return 1; }
            output_path = argv[++i];
        } else if (strcmp(argv[i], "-I") == 0) {
            if (i + 1 >= argc) { usage(argv[0]); return 1; }
            add_include_dir(argv[++i]);
        } else if (strncmp(argv[i], "-I", 2) == 0 && argv[i][2] != '\0') {
            add_include_dir(argv[i] + 2); /* -Idir, no space, same as gcc/clang */
        } else if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            usage(argv[0]); return 0;
        } else if (argv[i][0] != '-' && !input_path) {
            input_path = argv[i];
        } else {
            fprintf(stderr, "cc64: unrecognized argument '%s'\n", argv[i]);
            usage(argv[0]); return 1;
        }
    }
    if (!input_path || !output_path) { usage(argv[0]); return 1; }
    add_default_lib_dir(argv[0]);

    /* Phase 1: lexing. Turns the whole source file into g_toks[] up
     * front - see lexer.c's header comment for why that (rather than
     * producing tokens one at a time on demand) is what makes the
     * two-pass parsing strategy below possible. lex_file() also
     * follows any #include directives it finds, recursively - see
     * cc64.h's "HOW #include WORKS" note. */
    lex_file(input_path);

    /* Phase 2: the shallow declaration pass. After this, every
     * function's signature and every global's type is known, even
     * though not one function body has actually been parsed yet. */
    pass_a();
    if (!find_func("main")) fatal(0, "no 'main' function defined");
    if (find_func("main")->nparams != 0) fatal(0, "'main' must take no parameters in this version");

    g_out = fopen(output_path, "w");
    if (!g_out) { fprintf(stderr, "cc64: cannot open output '%s'\n", output_path); return 1; }

    /* Phase 3: emit the fixed program preamble and runtime library.
     * This all happens BEFORE any user code is generated, which is
     * why the trampoline below can simply `JSR __fn_main` - by the
     * time pass_b() (phase 4) generates __fn_main's actual code
     * further down in the file, the assembler's own two-pass design
     * (see c64asm.c) will resolve that forward reference correctly,
     * the same way it resolves every other label in this compiler's
     * output regardless of which order things appear in the file. */
    emit("; Generated by cc64 from %s", input_path);
    emit("; Assemble with: c64asm %s -o program.prg", output_path);
    emit(" ");
    emit_zp_equates();
    emit(".basic");
    emit("    LDA #14           ; switch to the lower/upper character set - required");
    emit("    JSR __CHROUT      ; for the PETSCII case mapping below to render as letters");
    emit("                      ; (the default charset only has graphics past $C0)");
    emit("    LDA #0");
    emit("    STA __rt_spidx");
    emit("    LDA #<__rt_cstack ; call-stack pointer starts at the base of its buffer -");
    emit("    STA __rt_csp      ; see codegen_stmt.c's emit_function() for how each");
    emit("    LDA #>__rt_cstack ; function's push/popframe routines use it to support");
    emit("    STA __rt_csp+1    ; recursion despite locals/params living at fixed addresses");
    emit("    JSR __fn_main");
    emit("    RTS");
    emit(" ");
    emit_runtime();
    emit_global_storage();

    /* Phase 4: the real parse. Parses each function body in turn and
     * immediately generates its code (see pass_b() in parser.c and
     * emit_function() in codegen_stmt.c) - by the time this returns,
     * the entire program's code has been written to g_out, and every
     * string literal encountered along the way has been recorded by
     * intern_string() (codegen_runtime.c) but not yet written out. */
    pass_b();

    /* Phase 5: now that pass_b() is done, every string literal in the
     * program is known, so their backing byte data can finally be
     * emitted - see emit_string_literals()'s own comment in
     * codegen_runtime.c for why this has to happen last. */
    emit_string_literals();

    emit("; ---- operand stack (128 16-bit slots, indexed by __rt_spidx) -------");
    emit("__rt_stack:");
    emit("    .fill 256, 0");
    emit("; ---- call stack (4096 bytes; see codegen_stmt.c's emit_function() ---");
    emit("; ---- and codegen_runtime.c's cstack-check comment for what this is)--");
    emit("__rt_cstack:");
    emit("    .fill 4096, 0");

    fclose(g_out);
    fprintf(stderr, "cc64: wrote %s\n", output_path);
    return 0;
}
